import type { Difficulty, Language, Problem } from './content';

type Spec = { title: string; topic: string; difficulty: Difficulty; description: string; task: string; explanation: string; input: string; output: string; solution: string };

function problem(id: number, language: Language, spec: Spec, pairedProblemId?: number): Problem {
  const starter = language === 'C'
    ? '#include <stdio.h>\n\nint main(void) {\n    // TODO\n    return 0;\n}'
    : language === 'C++'
      ? '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    // TODO\n}'
      : language === 'Python'
        ? '# 讀取輸入並完成程式\n'
        : language === 'SQL'
          ? 'SELECT\n  -- TODO\n;'
          : '# 輸入 GDB 指令\n';
  return {
    id,
    slug: `lab-${id}`,
    title: spec.title,
    language,
    difficulty: spec.difficulty,
    topic: spec.topic,
    track: language === 'SQL' ? '資料庫查詢' : language === 'GDB' ? '除錯實戰' : '陣列與字串',
    acceptance: Math.max(32, 86 - (id % 11) * 4),
    description: spec.description,
    task: spec.task,
    constraints: ['輸出格式必須與題目一致', '必須處理未顯示的邊界資料', '不得寫死範例結果'],
    examples: [{ input: spec.input, output: spec.output }],
    starter,
    solution: spec.solution,
    explanation: spec.explanation,
    hints: ['先把輸入輸出規格轉成明確步驟。', spec.explanation],
    checks: [{ label: '公開範例', input: spec.input, output: spec.output, tokens: language === 'GDB' ? spec.solution.split('\n') : ['main'] }],
    pairedProblemId,
  };
}

type Pair = Omit<Spec, 'title' | 'description' | 'task' | 'solution'> & { title: string; description: string; task: string; c: string; cpp: string };

const pairSpecs: Pair[] = [
  {title:'數值區間限制',topic:'陣列',difficulty:'簡單',description:'把每個整數限制在閉區間 [low, high]。',task:'第一行 n low high，第二行為序列；輸出調整後序列。',explanation:'小於 low 改成 low，大於 high 改成 high，其餘保持不變。',input:'5 0 10\n-3 4 12 7 0',output:'0 4 10 7 0',c:'#include <stdio.h>\nint main(void){int n,lo,hi,x;scanf("%d%d%d",&n,&lo,&hi);for(int i=0;i<n;i++){scanf("%d",&x);if(x<lo)x=lo;if(x>hi)x=hi;printf("%s%d",i?" ":"",x);}return 0;}',cpp:'#include <algorithm>\n#include <iostream>\nusing namespace std;\nint main(){int n,lo,hi,x;cin>>n>>lo>>hi;for(int i=0;i<n;i++){cin>>x;cout<<(i?" ":"")<<clamp(x,lo,hi);}}'},
  {title:'三數中位數',topic:'條件判斷',difficulty:'簡單',description:'找出三個不同整數排序後位於中間的值。',task:'讀入三個整數並輸出中位數。',explanation:'總和減去最大值與最小值即是中位數。',input:'9 2 6',output:'6',c:'#include <stdio.h>\nint main(void){int a,b,c,lo,hi;scanf("%d%d%d",&a,&b,&c);lo=a<b?a:b;lo=lo<c?lo:c;hi=a>b?a:b;hi=hi>c?hi:c;printf("%d",a+b+c-lo-hi);return 0;}',cpp:'#include <algorithm>\n#include <array>\n#include <iostream>\nusing namespace std;\nint main(){array<int,3>a;for(int&x:a)cin>>x;sort(a.begin(),a.end());cout<<a[1];}'},
  {title:'正負號切換次數',topic:'陣列',difficulty:'中等',description:'忽略零後，統計相鄰非零值正負號改變的次數。',task:'第一行 n、第二行序列；全部為零時輸出 0。',explanation:'保存上一個非零值的符號，遇到相反符號才增加答案。',input:'7\n-2 0 3 4 -1 0 -5',output:'2',c:'#include <stdio.h>\nint main(void){int n,x,prev=0,ans=0;scanf("%d",&n);while(n--){scanf("%d",&x);if(!x)continue;if(prev&&((prev<0)!=(x<0)))ans++;prev=x;}printf("%d",ans);return 0;}',cpp:'#include <iostream>\nusing namespace std;\nint main(){int n,x,prev=0,ans=0;cin>>n;while(n--){cin>>x;if(!x)continue;if(prev&&((prev<0)!=(x<0)))ans++;prev=x;}cout<<ans;}'},
  {title:'最長連續遞增段',topic:'陣列',difficulty:'中等',description:'找出嚴格遞增且位置連續的最長片段長度。',task:'n 至少為 1；輸出最大長度。',explanation:'若目前值大於前值就延長，否則從 1 重新開始。',input:'7\n1 2 5 3 4 6 0',output:'3',c:'#include <stdio.h>\nint main(void){int n,prev,x,run=1,best=1;scanf("%d%d",&n,&prev);for(int i=1;i<n;i++){scanf("%d",&x);run=x>prev?run+1:1;if(run>best)best=run;prev=x;}printf("%d",best);return 0;}',cpp:'#include <algorithm>\n#include <iostream>\nusing namespace std;\nint main(){int n,prev,x,run=1,best=1;cin>>n>>prev;for(int i=1;i<n;i++){cin>>x;run=x>prev?run+1:1;best=max(best,run);prev=x;}cout<<best;}'},
  {title:'環狀索引距離',topic:'數學',difficulty:'簡單',description:'在長度 n 的環上計算兩索引間最少步數。',task:'讀入 n、a、b，輸出順時針或逆時針的較短距離。',explanation:'直線距離為 d，繞另一側距離為 n-d。',input:'10 1 8',output:'3',c:'#include <stdio.h>\n#include <stdlib.h>\nint main(void){int n,a,b;scanf("%d%d%d",&n,&a,&b);int d=abs(a-b);printf("%d",d<n-d?d:n-d);return 0;}',cpp:'#include <algorithm>\n#include <cstdlib>\n#include <iostream>\nusing namespace std;\nint main(){int n,a,b;cin>>n>>a>>b;int d=abs(a-b);cout<<min(d,n-d);}'},
  {title:'文字長條圖',topic:'格式化輸出',difficulty:'簡單',description:'把每個非負計數畫成星號長條。',task:'第一行 n、第二行 n 個計數；每行輸出 index:stars。',explanation:'外層走訪項目，內層輸出指定數量星號。',input:'3\n2 0 4',output:'0:**\n1:\n2:****',c:'#include <stdio.h>\nint main(void){int n,x;scanf("%d",&n);for(int i=0;i<n;i++){scanf("%d",&x);printf("%d:",i);while(x--)putchar(\'*\');if(i+1<n)putchar(\'\\n\');}return 0;}',cpp:'#include <iostream>\n#include <string>\nusing namespace std;\nint main(){int n,x;cin>>n;for(int i=0;i<n;i++){cin>>x;cout<<i<<\':\'<<string(x,\'*\');if(i+1<n)cout<<\'\\n\';}}'},
  {title:'小寫異位詞判斷',topic:'字串',difficulty:'簡單',description:'判斷兩個只含 a-z 的字串是否為異位詞。',task:'字元次數完全相同輸出 true，否則 false。',explanation:'用 26 格計數陣列，一加一減後全部為零才相同。',input:'listen silent',output:'true',c:'#include <stdio.h>\nint main(void){char a[100005],b[100005];int c[26]={0},ok=1;scanf("%100000s%100000s",a,b);for(int i=0;a[i];i++)c[a[i]-\'a\']++;for(int i=0;b[i];i++)c[b[i]-\'a\']--;for(int i=0;i<26;i++)if(c[i])ok=0;printf("%s",ok?"true":"false");return 0;}',cpp:'#include <algorithm>\n#include <iostream>\n#include <string>\nusing namespace std;\nint main(){string a,b;cin>>a>>b;sort(a.begin(),a.end());sort(b.begin(),b.end());cout<<(a==b?"true":"false");}'},
  {title:'凱薩位移',topic:'字串',difficulty:'中等',description:'將小寫英文字母循環向右位移 k。',task:'k 可大於 26；輸出位移後字串。',explanation:'先對 k 取 26 餘數，再把字元轉為 0 到 25。',input:'2 zebra',output:'bgdtc',c:'#include <stdio.h>\nint main(void){int k;char s[100005];scanf("%d%100000s",&k,s);k%=26;for(int i=0;s[i];i++)s[i]=(char)(\'a\'+(s[i]-\'a\'+k)%26);printf("%s",s);return 0;}',cpp:'#include <iostream>\n#include <string>\nusing namespace std;\nint main(){int k;string s;cin>>k>>s;k%=26;for(char&c:s)c=char(\'a\'+(c-\'a\'+k)%26);cout<<s;}'},
  {title:'最長共同前綴',topic:'字串',difficulty:'中等',description:'找出 n 個非空單字共同的最長開頭。',task:'沒有共同前綴時輸出空行。',explanation:'以第一個單字為候選，逐一縮短到能匹配下一字串。',input:'3\nflower flow flight',output:'fl',c:'#include <stdio.h>\n#include <string.h>\nint main(void){int n;char p[1001],s[1001];scanf("%d%1000s",&n,p);while(--n){scanf("%1000s",s);int i=0;while(p[i]&&s[i]&&p[i]==s[i])i++;p[i]=0;}printf("%s",p);return 0;}',cpp:'#include <iostream>\n#include <string>\nusing namespace std;\nint main(){int n;string p,s;cin>>n>>p;while(--n){cin>>s;size_t i=0;while(i<p.size()&&i<s.size()&&p[i]==s[i])i++;p.resize(i);}cout<<p;}'},
  {title:'空白改底線',topic:'字串',difficulty:'簡單',description:'把一整行文字中的空格改成底線。',task:'保留其他字元與原順序。',explanation:'用整行讀取避免 scanf 或 cin 在空格處停止。',input:'learn C step by step',output:'learn_C_step_by_step',c:'#include <stdio.h>\nint main(void){char s[100005];fgets(s,sizeof(s),stdin);for(int i=0;s[i]&&s[i]!=\'\\n\';i++){if(s[i]==\' \')s[i]=\'_\';putchar(s[i]);}return 0;}',cpp:'#include <iostream>\n#include <string>\nusing namespace std;\nint main(){string s;getline(cin,s);for(char&c:s)if(c==\' \')c=\'_\';cout<<s;}'},
  {title:'階乘尾端零',topic:'數學',difficulty:'中等',description:'計算 n! 十進位表示尾端有幾個零。',task:'不可實際算出 n!。',explanation:'每個零來自因數 10，答案等於所有 5 的倍數貢獻量。',input:'100',output:'24',c:'#include <stdio.h>\nint main(void){long long n,ans=0;scanf("%lld",&n);for(long long p=5;p<=n;p*=5){ans+=n/p;if(p>n/5)break;}printf("%lld",ans);return 0;}',cpp:'#include <iostream>\nusing namespace std;\nint main(){long long n,ans=0;cin>>n;for(long long p=5;p<=n;p*=5){ans+=n/p;if(p>n/5)break;}cout<<ans;}'},
  {title:'質因數分解',topic:'數學',difficulty:'中等',description:'把大於 1 的整數分解成質數冪次。',task:'依質數遞增輸出 p^e，項目以空格分隔。',explanation:'試除到 p*p>n，最後剩餘大於 1 即為質因數。',input:'360',output:'2^3 3^2 5^1',c:'#include <stdio.h>\nint main(void){long long n;int first=1;scanf("%lld",&n);for(long long p=2;p*p<=n;p++){int e=0;while(n%p==0){n/=p;e++;}if(e){printf("%s%lld^%d",first?"":" ",p,e);first=0;}}if(n>1)printf("%s%lld^1",first?"":" ",n);return 0;}',cpp:'#include <iostream>\nusing namespace std;\nint main(){long long n;bool first=true;cin>>n;for(long long p=2;p*p<=n;p++){int e=0;while(n%p==0){n/=p;e++;}if(e){cout<<(first?"":" ")<<p<<\'^\'<<e;first=false;}}if(n>1)cout<<(first?"":" ")<<n<<"^1";}'},
  {title:'閏年判斷',topic:'日期',difficulty:'簡單',description:'依公曆規則判斷年份是否為閏年。',task:'可被 400 整除或可被 4 但不可被 100 整除時輸出 leap。',explanation:'把規則直接翻成布林運算並留意 and/or 優先順序。',input:'2000',output:'leap',c:'#include <stdio.h>\nint main(void){int y;scanf("%d",&y);int leap=y%400==0||(y%4==0&&y%100!=0);printf("%s",leap?"leap":"common");return 0;}',cpp:'#include <iostream>\nusing namespace std;\nint main(){int y;cin>>y;bool leap=y%400==0||(y%4==0&&y%100!=0);cout<<(leap?"leap":"common");}'},
  {title:'年度第幾天',topic:'日期',difficulty:'中等',description:'把年月日轉為該年度的序號日。',task:'日期保證合法；1 月 1 日為第 1 天。',explanation:'累加之前月份天數，二月依閏年調整。',input:'2024 3 1',output:'61',c:'#include <stdio.h>\nint main(void){int y,m,d;int days[]={0,31,28,31,30,31,30,31,31,30,31,30,31};scanf("%d%d%d",&y,&m,&d);if(y%400==0||(y%4==0&&y%100!=0))days[2]=29;for(int i=1;i<m;i++)d+=days[i];printf("%d",d);return 0;}',cpp:'#include <array>\n#include <iostream>\n#include <numeric>\nusing namespace std;\nint main(){int y,m,d;array<int,13>a{0,31,28,31,30,31,30,31,31,30,31,30,31};cin>>y>>m>>d;if(y%400==0||(y%4==0&&y%100!=0))a[2]=29;cout<<accumulate(a.begin()+1,a.begin()+m,d);}'},
  {title:'每列最大值',topic:'矩陣',difficulty:'簡單',description:'找出矩陣每一列的最大元素。',task:'第一行 r c，接著 r×c 個整數；每列輸出一個最大值。',explanation:'每列重新初始化最大值並完整走訪該列。',input:'2 3\n1 9 3\n-4 -2 -8',output:'9\n-2',c:'#include <stdio.h>\nint main(void){int r,c,x,b;scanf("%d%d",&r,&c);for(int i=0;i<r;i++){scanf("%d",&b);for(int j=1;j<c;j++){scanf("%d",&x);if(x>b)b=x;}printf("%d%s",b,i+1<r?"\\n":"");}return 0;}',cpp:'#include <algorithm>\n#include <iostream>\nusing namespace std;\nint main(){int r,c,x,b;cin>>r>>c;for(int i=0;i<r;i++){cin>>b;for(int j=1;j<c;j++){cin>>x;b=max(b,x);}cout<<b<<(i+1<r?"\\n":"");}}'},
  {title:'矩陣螺旋走訪',topic:'矩陣',difficulty:'困難',description:'由左上開始順時針輸出矩陣螺旋順序。',task:'矩陣可為非方陣，元素以空格分隔。',explanation:'維護 top、bottom、left、right 四個尚未走訪邊界。',input:'2 3\n1 2 3\n4 5 6',output:'1 2 3 6 5 4',c:'#include <stdio.h>\n#include <stdlib.h>\nint main(void){int r,c;scanf("%d%d",&r,&c);int*a=malloc(r*c*sizeof(int));for(int i=0;i<r*c;i++)scanf("%d",a+i);int t=0,b=r-1,l=0,h=c-1,k=0;while(t<=b&&l<=h){for(int j=l;j<=h;j++)printf("%s%d",k++?" ":"",a[t*c+j]);t++;for(int i=t;i<=b;i++)printf(" %d",a[i*c+h]);h--;if(t<=b){for(int j=h;j>=l;j--)printf(" %d",a[b*c+j]);b--;}if(l<=h){for(int i=b;i>=t;i--)printf(" %d",a[i*c+l]);l++;}}free(a);return 0;}',cpp:'#include <iostream>\n#include <vector>\nusing namespace std;\nint main(){int r,c;cin>>r>>c;vector a(r,vector<int>(c));for(auto&row:a)for(int&x:row)cin>>x;int t=0,b=r-1,l=0,h=c-1,k=0;auto out=[&](int x){cout<<(k++?" ":"")<<x;};while(t<=b&&l<=h){for(int j=l;j<=h;j++)out(a[t][j]);t++;for(int i=t;i<=b;i++)out(a[i][h]);h--;if(t<=b){for(int j=h;j>=l;j--)out(a[b][j]);b--;}if(l<=h){for(int i=b;i>=t;i--)out(a[i][l]);l++;}}}'},
  {title:'區間交集',topic:'雙指標',difficulty:'困難',description:'找出兩組已排序且各自不重疊閉區間的交集。',task:'輸入 n、m 後兩組區間；每行輸出一個交集。',explanation:'交集端點為 max(left) 與 min(right)，再移動較早結束的一方。',input:'2 2\n1 5\n10 14\n3 8\n11 12',output:'3 5\n11 12',c:'#include <stdio.h>\n#include <stdlib.h>\ntypedef struct{int l,r;}I;int main(void){int n,m;scanf("%d%d",&n,&m);I*a=malloc(n*sizeof(I)),*b=malloc(m*sizeof(I));for(int i=0;i<n;i++)scanf("%d%d",&a[i].l,&a[i].r);for(int i=0;i<m;i++)scanf("%d%d",&b[i].l,&b[i].r);int i=0,j=0,k=0;while(i<n&&j<m){int l=a[i].l>b[j].l?a[i].l:b[j].l,r=a[i].r<b[j].r?a[i].r:b[j].r;if(l<=r)printf("%s%d %d",k++?"\\n":"",l,r);if(a[i].r<b[j].r)i++;else j++;}free(a);free(b);}',cpp:'#include <algorithm>\n#include <iostream>\n#include <vector>\nusing namespace std;\nint main(){int n,m;cin>>n>>m;vector<pair<int,int>>a(n),b(m);for(auto&[l,r]:a)cin>>l>>r;for(auto&[l,r]:b)cin>>l>>r;int i=0,j=0,k=0;while(i<n&&j<m){int l=max(a[i].first,b[j].first),r=min(a[i].second,b[j].second);if(l<=r)cout<<(k++?"\\n":"")<<l<<\' \'<<r;if(a[i].second<b[j].second)i++;else j++;}}'},
  {title:'平衡二進位切段',topic:'前綴計數',difficulty:'中等',description:'計算可切出的最大片段數，使每段 0 與 1 數量相同。',task:'輸入保證整個字串的 0 與 1 數量相同。',explanation:'前綴平衡值每次回到零就完成一個最早可切片段。',input:'01001110',output:'3',c:'#include <stdio.h>\nint main(void){char s[100005];int balance=0,ans=0;scanf("%100000s",s);for(int i=0;s[i];i++){balance+=s[i]==\'1\'?1:-1;if(!balance)ans++;}printf("%d",ans);}',cpp:'#include <iostream>\n#include <string>\nusing namespace std;\nint main(){string s;int balance=0,ans=0;cin>>s;for(char c:s){balance+=c==\'1\'?1:-1;if(!balance)ans++;}cout<<ans;}'},
  {title:'快速模次方',topic:'位元運算',difficulty:'中等',description:'計算 base^exponent mod modulus。',task:'exponent 可很大，必須使用二進位快速冪。',explanation:'每輪平方底數，指數最低位為 1 時乘入答案。',input:'2 10 1000',output:'24',c:'#include <stdio.h>\nint main(void){long long a,e,m,r=1;scanf("%lld%lld%lld",&a,&e,&m);a%=m;while(e){if(e&1)r=r*a%m;a=a*a%m;e>>=1;}printf("%lld",r);}',cpp:'#include <iostream>\nusing namespace std;\nint main(){long long a,e,m,r=1;cin>>a>>e>>m;a%=m;while(e){if(e&1)r=r*a%m;a=a*a%m;e>>=1;}cout<<r;}'},
  {title:'下一個更大元素索引',topic:'單調堆疊',difficulty:'困難',description:'為每個位置找右側第一個嚴格更大元素的索引。',task:'不存在輸出 -1，索引由 0 開始。',explanation:'堆疊保存尚未找到答案且值單調遞減的索引。',input:'5\n2 1 4 3 5',output:'2 2 4 4 -1',c:'#include <stdio.h>\n#include <stdlib.h>\nint main(void){int n;scanf("%d",&n);int*a=malloc(n*sizeof(int)),*st=malloc(n*sizeof(int)),*ans=malloc(n*sizeof(int)),top=0;for(int i=0;i<n;i++){scanf("%d",&a[i]);ans[i]=-1;while(top&&a[st[top-1]]<a[i])ans[st[--top]]=i;st[top++]=i;}for(int i=0;i<n;i++)printf("%s%d",i?" ":"",ans[i]);free(a);free(st);free(ans);}',cpp:'#include <iostream>\n#include <stack>\n#include <vector>\nusing namespace std;\nint main(){int n;cin>>n;vector<int>a(n),ans(n,-1);stack<int>st;for(int i=0;i<n;i++){cin>>a[i];while(!st.empty()&&a[st.top()]<a[i]){ans[st.top()]=i;st.pop();}st.push(i);}for(int i=0;i<n;i++)cout<<(i?" ":"")<<ans[i];}'},
];

const pairedProblems = pairSpecs.flatMap((spec, index) => {
  const cId = 601 + index;
  const cppId = 621 + index;
  const base = { ...spec, title: spec.title, solution: spec.c };
  return [
    problem(cId, 'C', { ...base, title: `${spec.title}（C 完整程式）`, description: `${spec.description} 請使用 C 的陣列、指標或標準函式庫實作。`, task: `${spec.task} 提交可獨立編譯的 C 程式。` }, cppId),
    problem(cppId, 'C++', { ...base, title: `${spec.title}（C++ 完整程式）`, description: `${spec.description} 請使用 C++ 容器或標準演算法實作。`, task: `${spec.task} 提交可獨立編譯的 C++ 程式。`, solution: spec.cpp }, cId),
  ];
});

const pythonSpecs: Spec[] = [
  {title:'正規化 Unix 路徑',topic:'字串',difficulty:'中等',description:'移除重複斜線、單點與可回退的雙點片段。',task:'輸入絕對路徑，輸出正規化結果。',explanation:'以堆疊保存有效目錄名稱，遇到 .. 就彈出。',input:'/a//b/./c/../d',output:'/a/b/d',solution:"path=input().strip();parts=[]\nfor part in path.split('/'):\n if part in ('','.'):continue\n if part=='..':\n  if parts:parts.pop()\n else:parts.append(part)\nprint('/'+'/'.join(parts))"},
  {title:'遞迴攤平巢狀清單',topic:'遞迴',difficulty:'中等',description:'把任意層 JSON 整數清單攤平成一維。',task:'保留由左至右順序並輸出 JSON。',explanation:'遇到 list 遞迴，遇到整數直接加入答案。',input:'[1,[2,[3,4]],5]',output:'[1,2,3,4,5]',solution:"import json\ndata=json.loads(input());out=[]\ndef visit(value):\n if isinstance(value,list):\n  for item in value:visit(item)\n else:out.append(value)\nvisit(data);print(json.dumps(out,separators=(',',':')))"},
  {title:'依部門分組姓名',topic:'defaultdict',difficulty:'簡單',description:'把 JSON 紀錄依 department 分組。',task:'每組姓名與 key 都需排序後輸出 JSON。',explanation:'defaultdict(list) 可省略首次建立清單的分支。',input:'[{"name":"Ada","department":"R&D"},{"name":"Linus","department":"OS"},{"name":"Grace","department":"R&D"}]',output:'{"OS":["Linus"],"R&D":["Ada","Grace"]}',solution:"import json\nfrom collections import defaultdict\ngroups=defaultdict(list)\nfor row in json.loads(input()):groups[row['department']].append(row['name'])\nprint(json.dumps({k:sorted(groups[k]) for k in sorted(groups)},separators=(',',':')))"},
  {title:'最常見三個單字',topic:'Counter',difficulty:'中等',description:'輸出頻率最高的三個單字；同頻率按字母排序。',task:'輸入一行以空格分隔的小寫單字。',explanation:'排序 key 使用負頻率再接單字。',input:'c python c sql python c gdb sql',output:'c:3 python:2 sql:2',solution:"from collections import Counter\ncounts=Counter(input().split())\nitems=sorted(counts.items(),key=lambda item:(-item[1],item[0]))[:3]\nprint(' '.join(f'{word}:{count}' for word,count in items))"},
  {title:'游程字串解碼',topic:'字串',difficulty:'中等',description:'將字元後接正整數次數的編碼展開。',task:'次數可能有多位數，例如 a12。',explanation:'讀到字母後累積後方連續數字，再重複該字元。',input:'a3b2c1',output:'aaabbc',solution:"s=input().strip();out=[];i=0\nwhile i<len(s):\n ch=s[i];i+=1;j=i\n while j<len(s) and s[j].isdigit():j+=1\n out.append(ch*int(s[i:j]));i=j\nprint(''.join(out))"},
  {title:'IPv4 位址驗證',topic:'字串',difficulty:'中等',description:'判斷字串是否為四段十進位 IPv4。',task:'禁止前導零，且每段介於 0 到 255。',explanation:'先檢查段數，再逐段驗證字元、前導零與範圍。',input:'192.168.1.1',output:'true',solution:"parts=input().strip().split('.')\nok=len(parts)==4 and all(p.isdigit() and (p=='0' or not p.startswith('0')) and 0<=int(p)<=255 for p in parts)\nprint(str(ok).lower())"},
  {title:'矩陣順時針旋轉',topic:'矩陣',difficulty:'中等',description:'把 JSON 矩陣旋轉 90 度。',task:'矩陣非空且每列等長。',explanation:'先反轉列順序再以 zip 轉置。',input:'[[1,2,3],[4,5,6]]',output:'[[4,1],[5,2],[6,3]]',solution:"import json\nmatrix=json.loads(input())\nrotated=[list(row) for row in zip(*matrix[::-1])]\nprint(json.dumps(rotated,separators=(',',':')))"},
  {title:'指定顏色填滿',topic:'DFS',difficulty:'中等',description:'從指定格開始，把四向相連的原色改為新色。',task:'輸入 [grid,row,col,newColor] JSON。',explanation:'若新舊顏色不同，再以堆疊走訪同色鄰居。',input:'[[[1,1,0],[1,0,0]],0,0,2]',output:'[[2,2,0],[2,0,0]]',solution:"import json\ng,r,c,new=json.loads(input());old=g[r][c]\nif old!=new:\n stack=[(r,c)];g[r][c]=new\n while stack:\n  x,y=stack.pop()\n  for dx,dy in ((1,0),(-1,0),(0,1),(0,-1)):\n   nx,ny=x+dx,y+dy\n   if 0<=nx<len(g) and 0<=ny<len(g[0]) and g[nx][ny]==old:g[nx][ny]=new;stack.append((nx,ny))\nprint(json.dumps(g,separators=(',',':')))"},
  {title:'Dijkstra 最短距離',topic:'圖論',difficulty:'困難',description:'計算起點到每個節點的非負權重最短距離。',task:'輸入 [n,edges,start]，不可達輸出 -1。',explanation:'優先佇列每次取出目前最小距離，過期項目直接略過。',input:'[4,[[0,1,2],[0,2,5],[1,2,1],[2,3,3]],0]',output:'[0,2,3,6]',solution:"import heapq,json\nn,edges,start=json.loads(input());g=[[] for _ in range(n)]\nfor a,b,w in edges:g[a].append((b,w))\nd=[10**18]*n;d[start]=0;q=[(0,start)]\nwhile q:\n dist,node=heapq.heappop(q)\n if dist!=d[node]:continue\n for nxt,w in g[node]:\n  nd=dist+w\n  if nd<d[nxt]:d[nxt]=nd;heapq.heappush(q,(nd,nxt))\nprint(json.dumps([-1 if x==10**18 else x for x in d],separators=(',',':')))"},
  {title:'字典序拓撲排序',topic:'圖論',difficulty:'困難',description:'輸出有向無環圖中字典序最小的拓撲順序。',task:'節點為 0 到 n-1；輸入 [n,edges] JSON。',explanation:'把所有入度零節點放進最小堆，逐步移除邊。',input:'[4,[[0,2],[1,2],[1,3]]]',output:'[0,1,2,3]',solution:"import heapq,json\nn,edges=json.loads(input());g=[[] for _ in range(n)];degree=[0]*n\nfor a,b in edges:g[a].append(b);degree[b]+=1\nq=[i for i,x in enumerate(degree) if x==0];heapq.heapify(q);order=[]\nwhile q:\n node=heapq.heappop(q);order.append(node)\n for nxt in g[node]:\n  degree[nxt]-=1\n  if degree[nxt]==0:heapq.heappush(q,nxt)\nprint(json.dumps(order,separators=(',',':')))"},
  {title:'最長遞增子序列長度',topic:'二分搜尋',difficulty:'困難',description:'找出不要求位置連續的嚴格遞增子序列長度。',task:'輸入 JSON 整數陣列。',explanation:'tails[i] 保存長度 i+1 子序列可能的最小尾值。',input:'[10,9,2,5,3,7,101,18]',output:'4',solution:"import bisect,json\ntails=[]\nfor value in json.loads(input()):\n i=bisect.bisect_left(tails,value)\n if i==len(tails):tails.append(value)\n else:tails[i]=value\nprint(len(tails))"},
  {title:'子集合總和可達性',topic:'動態規劃',difficulty:'中等',description:'判斷是否可選部分正整數恰好湊成 target。',task:'輸入 [nums,target] JSON，輸出 true 或 false。',explanation:'集合保存目前可達總和，每個數只能由上一輪狀態使用一次。',input:'[[3,4,7,10],14]',output:'true',solution:"import json\nnums,target=json.loads(input());reachable={0}\nfor value in nums:reachable|={total+value for total in tuple(reachable) if total+value<=target}\nprint(str(target in reachable).lower())"},
  {title:'LRU 快取模擬',topic:'OrderedDict',difficulty:'困難',description:'模擬固定容量快取依序存取 key。',task:'輸入 [capacity,keys]，輸出由最舊到最新的 key。',explanation:'命中時移到尾端，超過容量就彈出最前端。',input:'[3,[1,2,3,1,4]]',output:'[3,1,4]',solution:"import json\nfrom collections import OrderedDict\ncapacity,keys=json.loads(input());cache=OrderedDict()\nfor key in keys:\n if key in cache:cache.move_to_end(key)\n else:cache[key]=None\n if len(cache)>capacity:cache.popitem(last=False)\nprint(json.dumps(list(cache),separators=(',',':')))"},
  {title:'CSV 團隊金額彙總',topic:'csv',difficulty:'中等',description:'讀取 team,amount 格式的多行資料並彙總。',task:'第一行為筆數，依 team 排序輸出 team,total。',explanation:'csv.reader 正確解析欄位，再用 defaultdict 累加。',input:'4\nA,10\nB,7\nA,5\nB,-2',output:'A,15\nB,5',solution:"import csv,sys\nfrom collections import defaultdict\nn=int(input());totals=defaultdict(int)\nfor team,amount in csv.reader([input() for _ in range(n)]):totals[team]+=int(amount)\nfor team in sorted(totals):print(f'{team},{totals[team]}')"},
  {title:'字典數值合併',topic:'dict',difficulty:'簡單',description:'合併兩個 JSON 物件，同名 key 的整數值相加。',task:'輸入一個含兩物件的 JSON 陣列，按 key 排序輸出。',explanation:'遍歷兩份 items 並以 get 提供預設零值。',input:'[{"a":2,"b":1},{"b":4,"c":3}]',output:'{"a":2,"b":5,"c":3}',solution:"import json\nleft,right=json.loads(input());merged={}\nfor source in (left,right):\n for key,value in source.items():merged[key]=merged.get(key,0)+value\nprint(json.dumps(dict(sorted(merged.items())),separators=(',',':')))"},
  {title:'日期間隔天數',topic:'datetime',difficulty:'中等',description:'計算排序日期清單中相鄰日期相差天數。',task:'輸入 JSON ISO 日期陣列並輸出差值陣列。',explanation:'date.fromisoformat 解析後可直接相減。',input:'["2026-01-01","2026-01-04","2026-02-01"]',output:'[3,28]',solution:"import json\nfrom datetime import date\ndates=[date.fromisoformat(x) for x in json.loads(input())]\nprint(json.dumps([(b-a).days for a,b in zip(dates,dates[1:])],separators=(',',':')))"},
  {title:'自寫 lower_bound',topic:'二分搜尋',difficulty:'中等',description:'找出排序陣列中第一個大於等於 target 的索引。',task:'輸入 [nums,target] JSON，不存在回傳陣列長度。',explanation:'維護半開區間 [left,right)，條件成立時收縮右界。',input:'[[1,3,3,7],3]',output:'1',solution:"import json\nnums,target=json.loads(input());left,right=0,len(nums)\nwhile left<right:\n mid=(left+right)//2\n if nums[mid]<target:left=mid+1\n else:right=mid\nprint(left)"},
  {title:'產生器分批取值',topic:'generator',difficulty:'中等',description:'以產生器每次產生固定大小的清單區塊。',task:'輸入 [values,size] JSON 並輸出所有區塊。',explanation:'yield 讓函式逐塊提供資料而不必一次複製所有結果。',input:'[[1,2,3,4,5],2]',output:'[[1,2],[3,4],[5]]',solution:"import json\nvalues,size=json.loads(input())\ndef batches(items,width):\n for start in range(0,len(items),width):yield items[start:start+width]\nprint(json.dumps(list(batches(values,size)),separators=(',',':')))"},
  {title:'擷取唯一 Email',topic:'regex',difficulty:'中等',description:'從文字擷取 Email，轉小寫、去重並排序。',task:'只需支援一般 ASCII 帳號與網域格式。',explanation:'findall 擷取候選，set 去重後再排序。',input:'Mail A@Test.com and b@test.org; again a@test.com',output:'["a@test.com","b@test.org"]',solution:"import json,re\ntext=input();emails=re.findall(r'[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}',text)\nprint(json.dumps(sorted({x.lower() for x in emails}),separators=(',',':')))"},
  {title:'庫存總值資料類別',topic:'dataclass',difficulty:'中等',description:'把 JSON 商品轉成資料類別並計算總庫存價值。',task:'每筆含 name、quantity、price；輸出兩位小數。',explanation:'dataclass 讓紀錄欄位明確，sum 搭配生成器計算。',input:'[{"name":"A","quantity":2,"price":3.5},{"name":"B","quantity":1,"price":4}]',output:'11.00',solution:"import json\nfrom dataclasses import dataclass\n@dataclass\nclass Item:name:str;quantity:int;price:float\nitems=[Item(**row) for row in json.loads(input())]\nprint(f'{sum(item.quantity*item.price for item in items):.2f}')"},
  {title:'安全讀取巢狀索引',topic:'例外處理',difficulty:'中等',description:'依包含 key 或索引的 JSON 路徑讀取巢狀資料。',task:'失敗時輸出 null，不得讓程式崩潰。',explanation:'逐層存取並捕捉 KeyError、IndexError、TypeError。',input:'[{"users":[{"name":"Ada"}]},["users",0,"name"]]',output:'"Ada"',solution:"import json\ndata,path=json.loads(input());current=data\ntry:\n for part in path:current=current[part]\nexcept (KeyError,IndexError,TypeError):current=None\nprint(json.dumps(current,separators=(',',':')))"},
];

const sqlSpecs: Spec[] = [
  {title:'專案未完成任務數',topic:'LEFT JOIN',difficulty:'中等',description:'projects 與 tasks 以 project_id 關聯。',task:'輸出每個專案未完成任務數，包含零筆者。',explanation:'條件 CASE 僅計算 done=0，LEFT JOIN 保留空專案。',input:'projects + tasks',output:'1|Compiler|2\n2|Docs|0',solution:"SELECT p.id,p.name,SUM(CASE WHEN t.done=0 THEN 1 ELSE 0 END) open_tasks FROM projects p LEFT JOIN tasks t ON t.project_id=p.id GROUP BY p.id,p.name ORDER BY p.id;"},
  {title:'三筆移動平均',topic:'窗口函式',difficulty:'困難',description:'metrics 含 day 與 value。',task:'輸出每一天與目前及前兩筆的平均，四捨五入一位。',explanation:'ROWS 2 PRECEDING 建立最多三列的移動窗口。',input:'metrics',output:'2026-01-01|10.0\n2026-01-02|15.0\n2026-01-03|20.0\n2026-01-04|30.0',solution:"SELECT day,ROUND(AVG(value) OVER(ORDER BY day ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),1) moving_avg FROM metrics ORDER BY day;"},
  {title:'每商品最新價格',topic:'ROW_NUMBER',difficulty:'中等',description:'prices 記錄商品不同生效日的價格。',task:'每商品只輸出最新一筆，日期相同時取較大 id。',explanation:'窗口列號以日期與 id 倒序，選 rn=1。',input:'prices',output:'1|12.0|2026-02-01\n2|8.0|2026-01-15',solution:"WITH ranked AS(SELECT product_id,price,effective_at,ROW_NUMBER()OVER(PARTITION BY product_id ORDER BY effective_at DESC,id DESC) rn FROM prices) SELECT product_id,price,effective_at FROM ranked WHERE rn=1 ORDER BY product_id;"},
  {title:'重複帳號配對',topic:'自連接',difficulty:'中等',description:'accounts 的 username 比較不分大小寫。',task:'每組重複只輸出 id 較小者在前的配對。',explanation:'自連接並用 a.id<b.id 避免自己配對與反向重複。',input:'accounts',output:'1|3',solution:"SELECT a.id,b.id FROM accounts a JOIN accounts b ON lower(a.username)=lower(b.username) AND a.id<b.id ORDER BY a.id,b.id;"},
  {title:'訂單編號缺口起點',topic:'NOT EXISTS',difficulty:'中等',description:'orders 的 order_no 為遞增唯一整數。',task:'列出每個已存在編號後第一個缺少編號，最大值之後不算。',explanation:'檢查 n+1 不存在，並排除目前最大編號。',input:'orders',output:'103\n107',solution:"SELECT a.order_no+1 missing_no FROM orders a WHERE a.order_no<(SELECT MAX(order_no) FROM orders) AND NOT EXISTS(SELECT 1 FROM orders b WHERE b.order_no=a.order_no+1) ORDER BY missing_no;"},
  {title:'從未售出商品',topic:'反連接',difficulty:'簡單',description:'products 與 sales 以 product_id 關聯。',task:'輸出沒有任何銷售紀錄的商品。',explanation:'LEFT JOIN 後右表主鍵為 NULL 即未配對。',input:'products + sales',output:'2|Mouse',solution:"SELECT p.id,p.name FROM products p LEFT JOIN sales s ON s.product_id=p.id WHERE s.id IS NULL ORDER BY p.id;"},
  {title:'高於團隊平均薪資',topic:'關聯子查詢',difficulty:'中等',description:'employees 含 team 與 salary。',task:'列出薪資嚴格高於自己團隊平均的員工。',explanation:'關聯子查詢依外層 team 計算該組平均。',input:'employees',output:'2|Ada|A|30\n4|Linus|B|50',solution:"SELECT e.id,e.name,e.team,e.salary FROM employees e WHERE e.salary>(SELECT AVG(x.salary) FROM employees x WHERE x.team=e.team) ORDER BY e.id;"},
  {title:'逐筆庫存餘額',topic:'窗口函式',difficulty:'中等',description:'movements 含 product_id、seq、quantity。',task:'依商品與序號輸出每筆異動後庫存。',explanation:'分組窗口 SUM 搭配 ROWS 可取得逐列累積值。',input:'movements',output:'1|1|10|10\n1|2|-3|7\n2|1|5|5',solution:"SELECT product_id,seq,quantity,SUM(quantity)OVER(PARTITION BY product_id ORDER BY seq ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) stock FROM movements ORDER BY product_id,seq;"},
  {title:'分類銷售占比',topic:'窗口函式',difficulty:'困難',description:'sales 含 category 與 amount。',task:'輸出每筆金額占同分類總額百分比，四捨五入一位。',explanation:'窗口 SUM 保留明細，同時提供分類分母。',input:'sales',output:'A|30|30.0\nA|70|70.0\nB|50|100.0',solution:"SELECT category,amount,ROUND(100.0*amount/SUM(amount)OVER(PARTITION BY category),1) percentage FROM sales ORDER BY category,amount;"},
  {title:'使用者首末事件',topic:'MIN MAX',difficulty:'簡單',description:'events 含 user_id 與 occurred_at。',task:'每位使用者輸出第一與最後事件時間。',explanation:'同一分組內以 MIN 和 MAX 取得邊界。',input:'events',output:'1|09:00|11:00\n2|08:30|08:30',solution:"SELECT user_id,MIN(occurred_at) first_at,MAX(occurred_at) last_at FROM events GROUP BY user_id ORDER BY user_id;"},
  {title:'分類樹完整路徑',topic:'遞迴 CTE',difficulty:'困難',description:'categories 以 parent_id 建立樹。',task:'由根向下輸出 id 與用 / 連接的完整路徑。',explanation:'遞迴列把父路徑與子名稱串接。',input:'categories',output:'1|Root\n2|Root/Books\n3|Root/Books/C',solution:"WITH RECURSIVE tree(id,path)AS(SELECT id,name FROM categories WHERE parent_id IS NULL UNION ALL SELECT c.id,tree.path||'/'||c.name FROM categories c JOIN tree ON c.parent_id=tree.id) SELECT id,path FROM tree ORDER BY id;"},
  {title:'連續兩天出席配對',topic:'日期連接',difficulty:'中等',description:'attendance 含 user_id 與 day，且每日唯一。',task:'輸出每個連續兩天的起始日。',explanation:'自連接同使用者且第二天等於第一天加一日。',input:'attendance',output:'1|2026-01-01\n1|2026-01-02',solution:"SELECT a.user_id,a.day FROM attendance a JOIN attendance b ON b.user_id=a.user_id AND b.day=date(a.day,'+1 day') ORDER BY a.user_id,a.day;"},
  {title:'訂單金額分桶',topic:'CASE',difficulty:'簡單',description:'orders 含 amount。',task:'統計 small(<50)、medium(<100)、large 三個級距。',explanation:'CASE 先產生桶名稱，再對桶分組計數。',input:'orders',output:'large|1\nmedium|2\nsmall|1',solution:"WITH labeled AS(SELECT CASE WHEN amount<50 THEN 'small' WHEN amount<100 THEN 'medium' ELSE 'large' END bucket FROM orders) SELECT bucket,COUNT(*) FROM labeled GROUP BY bucket ORDER BY bucket;"},
  {title:'季度營收橫向統計',topic:'條件彙總',difficulty:'中等',description:'revenue 含 team、quarter、amount。',task:'每隊輸出 Q1 到 Q4 四欄總額。',explanation:'四個條件 SUM 將季度列轉成欄。',input:'revenue',output:'A|10|20|0|5\nB|7|0|0|0',solution:"SELECT team,SUM(CASE WHEN quarter=1 THEN amount ELSE 0 END) q1,SUM(CASE WHEN quarter=2 THEN amount ELSE 0 END) q2,SUM(CASE WHEN quarter=3 THEN amount ELSE 0 END) q3,SUM(CASE WHEN quarter=4 THEN amount ELSE 0 END) q4 FROM revenue GROUP BY team ORDER BY team;"},
  {title:'買過所有商品的客戶',topic:'關聯除法',difficulty:'困難',description:'purchases 記錄客戶購買的 product_id。',task:'輸出買過 products 表中每一種商品的客戶。',explanation:'每客戶不同商品數等於商品總數，即完成全集覆蓋。',input:'customers + products + purchases',output:'1|Ada',solution:"SELECT c.id,c.name FROM customers c JOIN purchases p ON p.customer_id=c.id GROUP BY c.id,c.name HAVING COUNT(DISTINCT p.product_id)=(SELECT COUNT(*) FROM products) ORDER BY c.id;"},
  {title:'部門第二位員工',topic:'ROW_NUMBER',difficulty:'中等',description:'employees 依部門薪資倒序、id 正序排名。',task:'每部門輸出恰好第 2 列，不合併同薪。',explanation:'ROW_NUMBER 對每列給唯一序號，適合精確取第二列。',input:'employees',output:'2|A|90\n5|B|70',solution:"WITH ranked AS(SELECT id,department,salary,ROW_NUMBER()OVER(PARTITION BY department ORDER BY salary DESC,id) rn FROM employees) SELECT id,department,salary FROM ranked WHERE rn=2 ORDER BY department;"},
  {title:'工作階段分鐘數',topic:'日期運算',difficulty:'中等',description:'sessions 含 started_at 與 ended_at。',task:'輸出每個 session 的整數分鐘數。',explanation:'julianday 差乘 1440，ROUND 消除浮點微差。',input:'sessions',output:'1|30\n2|90',solution:"SELECT id,CAST(ROUND((julianday(ended_at)-julianday(started_at))*1440) AS INTEGER) minutes FROM sessions ORDER BY id;"},
  {title:'缺少的行事曆日期',topic:'遞迴 CTE',difficulty:'困難',description:'events 含 day，需找最小到最大日期間沒有事件的日子。',task:'每天最多一筆；輸出所有缺日。',explanation:'遞迴生成完整日期序列，再用 NOT EXISTS 做差集。',input:'events',output:'2026-01-02\n2026-01-04',solution:"WITH RECURSIVE calendar(day)AS(SELECT MIN(day) FROM events UNION ALL SELECT date(day,'+1 day') FROM calendar WHERE day<(SELECT MAX(day) FROM events)) SELECT day FROM calendar WHERE NOT EXISTS(SELECT 1 FROM events e WHERE e.day=calendar.day) ORDER BY day;"},
  {title:'Email 去重保留最早帳號',topic:'窗口函式',difficulty:'中等',description:'users 的 email 比較不分大小寫。',task:'每個非 NULL email 只保留最小 id 的使用者。',explanation:'ROW_NUMBER 依正規化 email 分組並以 id 排序。',input:'users',output:'1|A@Test.com\n3|b@test.com',solution:"WITH ranked AS(SELECT id,email,ROW_NUMBER()OVER(PARTITION BY lower(email) ORDER BY id) rn FROM users WHERE email IS NOT NULL) SELECT id,email FROM ranked WHERE rn=1 ORDER BY id;"},
  {title:'月營收成長額',topic:'LAG',difficulty:'困難',description:'orders 含 month 與 amount。',task:'先彙總每月，再輸出與前月的營收差；首月為 NULL。',explanation:'分組結果再使用 LAG，避免在同層混用彙總與窗口。',input:'orders',output:'2026-01|100|\n2026-02|140|40\n2026-03|90|-50',solution:"WITH monthly AS(SELECT month,SUM(amount) revenue FROM orders GROUP BY month) SELECT month,revenue,revenue-LAG(revenue)OVER(ORDER BY month) growth FROM monthly ORDER BY month;"},
  {title:'課程加權平均分數',topic:'JOIN',difficulty:'中等',description:'scores 連接 assignments 的 weight。',task:'每位學生輸出依權重計算的平均，四捨五入一位。',explanation:'分子為 score*weight 總和，分母為 weight 總和。',input:'students + scores + assignments',output:'1|Ada|86.0\n2|Linus|70.0',solution:"SELECT s.id,s.name,ROUND(SUM(sc.score*a.weight)/SUM(a.weight),1) weighted_score FROM students s JOIN scores sc ON sc.student_id=s.id JOIN assignments a ON a.id=sc.assignment_id GROUP BY s.id,s.name ORDER BY s.id;"},
];

const gdbRows: Array<[string,string,Difficulty,string,string,string,string,string,string]> = [
  ['完成目前函式','流程控制','簡單','執行到目前函式 return，並印出回傳值。','依序使用 finish 與 print。','finish 會跑到呼叫者並保存回傳值於 $rax 等便利資訊。','停在 compute 內','回到呼叫者並顯示值','finish\nprint $rax'],
  ['執行到指定行','流程控制','簡單','在目前 frame 執行到第 80 行。','不建立永久中斷點。','until 適合快速越過目前迴圈。','停在 72 行','停在 80 行','until 80'],
  ['略過前三次命中','中斷點','中等','讓 breakpoint 2 前三次命中不暫停。','設定 ignore count。','ignore N COUNT 會忽略接下來 COUNT 次。','breakpoint 2','第 4 次才暫停','ignore 2 3\ncontinue'],
  ['中斷點自動記錄','命令清單','困難','breakpoint 1 命中時安靜印出 i 並繼續。','建立 commands 區塊。','silent 抑制預設訊息，commands 以 end 結束。','breakpoint 1','自動輸出 i','commands 1\nsilent\nprintf "i=%d\\n", i\ncontinue\nend'],
  ['監看指標位置','watchpoint','中等','監看 ptr 指向位置本身，即使 ptr 變動仍追蹤目前位置。','使用 -location。','watch -location 監看記憶體位置運算式。','ptr','寫入時暫停','watch -location *ptr\ncontinue'],
  ['查看 C 字串','記憶體','簡單','把 name 指向內容當成零結尾字串顯示。','使用 x 的 string 格式。','x/s 會由指定地址讀到 NUL。','name','字串內容','x/s name'],
  ['查看即將執行指令','組合語言','中等','從程式計數器起顯示 10 條機器指令。','使用 instruction 格式。','x/10i $pc 以目前指令位址開始反組譯。','paused','10 instructions','x/10i $pc'],
  ['開啟來源版面','TUI','簡單','在終端介面顯示來源碼視窗。','切換 layout src。','layout src 會保留命令列並顯示目前來源。','terminal','source window','layout src'],
  ['列出函式附近來源','來源碼','簡單','列出 parse 函式周圍的來源行。','使用 list 並指定函式。','list function 會定位函式定義附近。','parse','source lines','list parse'],
  ['列印動態陣列','顯示資料','中等','以 arr 起點和 len 顯示連續元素。','使用 GDB 人工陣列語法。','*arr@len 把連續記憶體視為陣列。','arr,len','array values','print *arr@len'],
  ['檢查結構型別','型別資訊','簡單','顯示 struct Node 的完整欄位定義。','使用 ptype。','ptype 顯示型別與成員。','struct Node','field layout','ptype struct Node'],
  ['關閉分頁提示','顯示設定','簡單','讓長輸出不再出現 Type return to continue。','修改 pagination 設定。','批次除錯時常先關閉分頁。','long output','continuous output','set pagination off'],
  ['儲存中斷點','中斷點','中等','把目前所有 breakpoint 儲存到 breaks.gdb。','使用 save breakpoints。','輸出檔之後可用 source 載回。','configured breakpoints','breaks.gdb','save breakpoints breaks.gdb'],
  ['載入除錯指令檔','自動化','簡單','執行 debug.gdb 中的 GDB 命令。','使用 source。','source 逐行執行命令檔。','debug.gdb','commands loaded','source debug.gdb'],
  ['反向執行一步','反向除錯','困難','已啟用 process record，回到上一個來源行。','使用 reverse-step。','反向除錯需先有執行記錄。','recording active','previous source line','reverse-step'],
  ['開始完整執行記錄','反向除錯','困難','啟用可供 reverse 命令使用的軟體記錄。','使用 record full。','record full 記錄指令與資料變化。','paused process','recording enabled','record full'],
  ['捕捉 fork','多程序','中等','程式呼叫 fork 時暫停。','建立 fork catchpoint。','catch fork 在產生子程序前後提供檢查點。','forking app','stop at fork','catch fork\ncontinue'],
  ['跟隨子程序','多程序','中等','fork 後讓 GDB 跟隨 child。','設定 follow-fork-mode。','預設跟隨 parent，可切換到 child。','before fork','debug child','set follow-fork-mode child\ncontinue'],
  ['保留父子程序','多程序','困難','fork 後不自動 detach 另一個程序。','關閉 detach-on-fork。','可搭配 inferiors 在父子程序間切換。','multi-process','both attached','set detach-on-fork off\ncontinue'],
  ['單執行緒步進','執行緒','困難','step 時只允許目前執行緒執行。','設定 scheduler-locking step。','只在單步期間鎖住其他執行緒。','multi-thread pause','deterministic step','set scheduler-locking step\nstep'],
];

const pythonProblems = pythonSpecs.slice(0, 20).map((spec, index) => problem(641 + index, 'Python', spec));
const sqlProblems = sqlSpecs.slice(0, 20).map((spec, index) => problem(661 + index, 'SQL', spec));
const gdbProblems = gdbRows.map(([title,topic,difficulty,description,task,explanation,input,output,solution], index) => problem(681 + index, 'GDB', { title,topic,difficulty,description,task,explanation,input,output,solution }));

export const uniqueDrillProblemsV2: Problem[] = [...pairedProblems, ...pythonProblems, ...sqlProblems, ...gdbProblems];
