import type { Difficulty, Language, Problem } from './content';

type Spec = {
  title: string;
  topic: string;
  difficulty: Difficulty;
  description: string;
  task: string;
  starter: string;
  solution: string;
  explanation: string;
  input: string;
  output: string;
};

function makeProblem(id: number, language: Language, spec: Spec, pairedProblemId?: number): Problem {
  return {
    id,
    slug: 'lab-' + id,
    title: spec.title,
    language,
    difficulty: spec.difficulty,
    topic: spec.topic,
    track: language === 'SQL' ? '資料庫查詢' : language === 'GDB' ? '除錯實戰' : '陣列與字串',
    acceptance: Math.max(35, 84 - (id % 12) * 4),
    description: spec.description,
    task: spec.task,
    constraints: ['輸出格式必須與題目一致', '需處理範例以外的隱藏測試', '不得寫死範例答案'],
    examples: [{ input: spec.input, output: spec.output }],
    starter: spec.starter,
    solution: spec.solution,
    explanation: spec.explanation,
    hints: ['先確認輸入與輸出的資料型態。', spec.explanation],
    checks: [
      { label: '公開範例', input: spec.input, output: spec.output, tokens: ['main'] },
      { label: '隱藏邊界', input: '隱藏測試', output: '通過', tokens: ['main'] },
    ],
    pairedProblemId,
  };
}

const cStarter = "#include <stdio.h>\n\nint main(void) {\n    // TODO\n    return 0;\n}";
const cppStarter = "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    // TODO\n    return 0;\n}";

type PairSpec = Omit<Spec, 'title' | 'starter' | 'solution'> & { title: string; c: string; cpp: string };

const pairSpecs: PairSpec[] = [
  { title:'正數總和', topic:'陣列', difficulty:'簡單', description:'只加總序列中大於零的整數。', task:'第一行 n、第二行 n 個整數；輸出正數總和。', explanation:'一次走訪並以 value > 0 篩選，時間 O(n)。', input:'5\n-2 7 0 3 -1', output:'10', c:"#include <stdio.h>\nint main(void){int n,x;long long s=0;scanf(\"%d\",&n);while(n--){scanf(\"%d\",&x);if(x>0)s+=x;}printf(\"%lld\",s);}", cpp:"#include <iostream>\nusing namespace std;\nint main(){int n,x;long long s=0;cin>>n;while(n--){cin>>x;if(x>0)s+=x;}cout<<s;}" },
  { title:'偶數個數', topic:'陣列', difficulty:'簡單', description:'統計序列中可被 2 整除的整數。', task:'讀入 n 個整數並輸出偶數數量，負偶數也要計入。', explanation:'餘數為零即為偶數。', input:'6\n1 2 -4 7 8 9', output:'3', c:"#include <stdio.h>\nint main(void){int n,x,c=0;scanf(\"%d\",&n);for(int i=0;i<n;i++){scanf(\"%d\",&x);c+=x%2==0;}printf(\"%d\",c);}", cpp:"#include <iostream>\nusing namespace std;\nint main(){int n,x,c=0;cin>>n;for(int i=0;i<n;i++){cin>>x;c+=x%2==0;}cout<<c;}" },
  { title:'最大值索引', topic:'陣列', difficulty:'簡單', description:'找出第一次出現最大值的位置。', task:'索引由 0 開始；最大值重複時保留最早位置。', explanation:'只在嚴格更大時更新，便能保留第一次索引。', input:'5\n4 9 2 9 1', output:'1', c:"#include <stdio.h>\nint main(void){int n,b,x,idx=0;scanf(\"%d%d\",&n,&b);for(int i=1;i<n;i++){scanf(\"%d\",&x);if(x>b){b=x;idx=i;}}printf(\"%d\",idx);}", cpp:"#include <algorithm>\n#include <iostream>\n#include <vector>\nusing namespace std;\nint main(){int n;cin>>n;vector<int>a(n);for(int&x:a)cin>>x;cout<<max_element(a.begin(),a.end())-a.begin();}" },
  { title:'第二大不同值', topic:'陣列', difficulty:'中等', description:'找出第二大的不同整數。', task:'輸入保證至少包含兩種不同值。', explanation:'維護最大與次大，重複最大值不可覆寫次大。', input:'6\n7 2 7 5 4 5', output:'5', c:"#include <limits.h>\n#include <stdio.h>\nint main(void){int n,x,a=INT_MIN,b=INT_MIN;scanf(\"%d\",&n);while(n--){scanf(\"%d\",&x);if(x>a){b=a;a=x;}else if(x<a&&x>b)b=x;}printf(\"%d\",b);}", cpp:"#include <iostream>\n#include <set>\nusing namespace std;\nint main(){int n,x;cin>>n;set<int>s;while(n--){cin>>x;s.insert(x);}auto it=s.rbegin();cout<<*++it;}" },
  { title:'陣列右旋', topic:'陣列', difficulty:'中等', description:'將序列循環向右移動 k 格。', task:'k 可能大於 n；輸出旋轉後序列。', explanation:'先計算 k %= n，再映射來源索引。', input:'5 2\n1 2 3 4 5', output:'4 5 1 2 3', c:"#include <stdio.h>\n#include <stdlib.h>\nint main(void){int n,k;scanf(\"%d%d\",&n,&k);int*a=malloc(n*sizeof(int));for(int i=0;i<n;i++)scanf(\"%d\",a+i);k%=n;for(int i=0;i<n;i++)printf(\"%s%d\",i?\" \":\"\",a[(i-k+n)%n]);free(a);}", cpp:"#include <algorithm>\n#include <iostream>\n#include <vector>\nusing namespace std;\nint main(){int n,k;cin>>n>>k;vector<int>a(n);for(int&x:a)cin>>x;k%=n;rotate(a.begin(),a.end()-k,a.end());for(int i=0;i<n;i++)cout<<(i?\" \":\"\")<<a[i];}" },
  { title:'排序序列去重', topic:'雙指標', difficulty:'簡單', description:'移除已排序序列中的重複值。', task:'輸出不同值並維持遞增順序。', explanation:'相同值相鄰，只要比較最後輸出值。', input:'7\n1 1 2 2 2 4 5', output:'1 2 4 5', c:"#include <stdio.h>\nint main(void){int n,x,last=0,first=1;scanf(\"%d\",&n);while(n--){scanf(\"%d\",&x);if(first||x!=last){printf(\"%s%d\",first?\"\":\" \",x);last=x;first=0;}}}", cpp:"#include <algorithm>\n#include <iostream>\n#include <vector>\nusing namespace std;\nint main(){int n;cin>>n;vector<int>a(n);for(int&x:a)cin>>x;a.erase(unique(a.begin(),a.end()),a.end());for(int i=0;i<(int)a.size();i++)cout<<(i?\" \":\"\")<<a[i];}" },
  { title:'回文判斷', topic:'字串', difficulty:'簡單', description:'判斷字串是否左右對稱。', task:'回文輸出 true，否則輸出 false。', explanation:'左右指標只需走訪一半字串。', input:'level', output:'true', c:"#include <stdio.h>\n#include <string.h>\nint main(void){char s[100005];scanf(\"%100000s\",s);int l=0,r=strlen(s)-1;while(l<r&&s[l]==s[r]){l++;r--;}printf(\"%s\",l>=r?\"true\":\"false\");}", cpp:"#include <algorithm>\n#include <iostream>\n#include <string>\nusing namespace std;\nint main(){string s;cin>>s;cout<<(equal(s.begin(),s.begin()+s.size()/2,s.rbegin())?\"true\":\"false\");}" },
  { title:'第一個不重複字元', topic:'字串', difficulty:'中等', description:'找出第一個只出現一次的字元索引。', task:'不存在時輸出 -1。', explanation:'第一輪計數，第二輪依原順序尋找次數一。', input:'swiss', output:'1', c:"#include <stdio.h>\nint main(void){char s[100005];int c[256]={0},ans=-1;scanf(\"%100000s\",s);for(int i=0;s[i];i++)c[(unsigned char)s[i]]++;for(int i=0;s[i];i++)if(c[(unsigned char)s[i]]==1){ans=i;break;}printf(\"%d\",ans);}", cpp:"#include <array>\n#include <iostream>\n#include <string>\nusing namespace std;\nint main(){string s;cin>>s;array<int,256>c{};for(unsigned char x:s)c[x]++;int ans=-1;for(int i=0;i<(int)s.size();i++)if(c[(unsigned char)s[i]]==1){ans=i;break;}cout<<ans;}" },
  { title:'最大公因數', topic:'數學', difficulty:'簡單', description:'使用歐幾里得演算法求 gcd。', task:'讀入兩個非負整數並輸出最大公因數。', explanation:'反覆用餘數取代較大數，直到第二數為零。', input:'84 30', output:'6', c:"#include <stdio.h>\nint main(void){long long a,b;scanf(\"%lld%lld\",&a,&b);while(b){long long r=a%b;a=b;b=r;}printf(\"%lld\",a);}", cpp:"#include <iostream>\n#include <numeric>\nusing namespace std;\nint main(){long long a,b;cin>>a>>b;cout<<gcd(a,b);}" },
  { title:'最小公倍數', topic:'數學', difficulty:'中等', description:'求兩個正整數的最小公倍數。', task:'先除後乘以降低溢位風險。', explanation:'lcm = a / gcd(a,b) * b。', input:'12 18', output:'36', c:"#include <stdio.h>\nlong long g(long long a,long long b){while(b){long long r=a%b;a=b;b=r;}return a;}\nint main(void){long long a,b;scanf(\"%lld%lld\",&a,&b);printf(\"%lld\",a/g(a,b)*b);}", cpp:"#include <iostream>\n#include <numeric>\nusing namespace std;\nint main(){long long a,b;cin>>a>>b;cout<<lcm(a,b);}" },
  { title:'質數數量', topic:'數學', difficulty:'中等', description:'計算 2 到 n 的質數數量。', task:'使用篩法，不能逐數試除到 n。', explanation:'由 p*p 開始標記每個質數的倍數。', input:'20', output:'8', c:"#include <stdio.h>\n#include <stdlib.h>\nint main(void){int n,c=0;scanf(\"%d\",&n);char*p=calloc(n+1,1);for(int i=2;i<=n;i++)p[i]=1;for(int i=2;i*i<=n;i++)if(p[i])for(int j=i*i;j<=n;j+=i)p[j]=0;for(int i=2;i<=n;i++)c+=p[i];printf(\"%d\",c);free(p);}", cpp:"#include <iostream>\n#include <vector>\nusing namespace std;\nint main(){int n,c=0;cin>>n;vector<bool>p(n+1,true);if(n>=0)p[0]=false;if(n>=1)p[1]=false;for(int i=2;i*i<=n;i++)if(p[i])for(int j=i*i;j<=n;j+=i)p[j]=false;for(bool x:p)c+=x;cout<<c;}" },
  { title:'費氏數列', topic:'動態規劃', difficulty:'簡單', description:'計算 F(0)=0、F(1)=1 的第 n 項。', task:'使用 O(1) 額外空間。', explanation:'只保留相鄰兩項即可推進。', input:'10', output:'55', c:"#include <stdio.h>\nint main(void){int n;long long a=0,b=1;scanf(\"%d\",&n);while(n--){long long t=a+b;a=b;b=t;}printf(\"%lld\",a);}", cpp:"#include <iostream>\nusing namespace std;\nint main(){int n;long long a=0,b=1;cin>>n;while(n--){long long t=a+b;a=b;b=t;}cout<<a;}" },
  { title:'矩陣邊框總和', topic:'矩陣', difficulty:'中等', description:'計算矩陣最外圈元素總和。', task:'單列或單欄元素不可重複計算。', explanation:'逐格判斷是否位於四條邊界。', input:'3 3\n1 2 3\n4 5 6\n7 8 9', output:'40', c:"#include <stdio.h>\nint main(void){int r,c,x;long long s=0;scanf(\"%d%d\",&r,&c);for(int i=0;i<r;i++)for(int j=0;j<c;j++){scanf(\"%d\",&x);if(!i||!j||i==r-1||j==c-1)s+=x;}printf(\"%lld\",s);}", cpp:"#include <iostream>\nusing namespace std;\nint main(){int r,c,x;long long s=0;cin>>r>>c;for(int i=0;i<r;i++)for(int j=0;j<c;j++){cin>>x;if(!i||!j||i+1==r||j+1==c)s+=x;}cout<<s;}" },
  { title:'方陣轉置', topic:'矩陣', difficulty:'中等', description:'輸出 n×n 方陣的轉置。', task:'輸出第 i,j 格為原矩陣第 j,i 格。', explanation:'讀完矩陣後交換索引輸出。', input:'2\n1 2\n3 4', output:'1 3\n2 4', c:"#include <stdio.h>\n#include <stdlib.h>\nint main(void){int n;scanf(\"%d\",&n);int*a=malloc(n*n*sizeof(int));for(int i=0;i<n*n;i++)scanf(\"%d\",a+i);for(int i=0;i<n;i++){for(int j=0;j<n;j++)printf(\"%s%d\",j?\" \":\"\",a[j*n+i]);if(i+1<n)puts(\"\");}free(a);}", cpp:"#include <iostream>\n#include <vector>\nusing namespace std;\nint main(){int n;cin>>n;vector a(n,vector<int>(n));for(auto&r:a)for(int&x:r)cin>>x;for(int i=0;i<n;i++){for(int j=0;j<n;j++)cout<<(j?\" \":\"\")<<a[j][i];if(i+1<n)cout<<'\\n';}}" },
  { title:'合併排序陣列', topic:'雙指標', difficulty:'中等', description:'合併兩個遞增序列並保留重複值。', task:'輸出完整遞增序列。', explanation:'兩個指標每次取較小值，時間 O(n+m)。', input:'3 4\n1 4 8\n2 2 6 9', output:'1 2 2 4 6 8 9', c:"#include <stdio.h>\n#include <stdlib.h>\nint main(void){int n,m;scanf(\"%d%d\",&n,&m);int*a=malloc(n*sizeof(int)),*b=malloc(m*sizeof(int));for(int i=0;i<n;i++)scanf(\"%d\",a+i);for(int j=0;j<m;j++)scanf(\"%d\",b+j);int i=0,j=0,k=0;while(i<n||j<m){int x=j==m||(i<n&&a[i]<=b[j])?a[i++]:b[j++];printf(\"%s%d\",k++?\" \":\"\",x);}free(a);free(b);}", cpp:"#include <algorithm>\n#include <iostream>\n#include <iterator>\n#include <vector>\nusing namespace std;\nint main(){int n,m;cin>>n>>m;vector<int>a(n),b(m),o(n+m);for(int&x:a)cin>>x;for(int&x:b)cin>>x;merge(a.begin(),a.end(),b.begin(),b.end(),o.begin());for(int i=0;i<n+m;i++)cout<<(i?\" \":\"\")<<o[i];}" },
  { title:'插入位置', topic:'二分搜尋', difficulty:'中等', description:'尋找第一個大於等於 target 的索引。', task:'輸入遞增序列；不存在時輸出 n。', explanation:'維護半開區間 [left,right)。', input:'5 6\n1 3 6 6 9', output:'2', c:"#include <stdio.h>\n#include <stdlib.h>\nint main(void){int n,t;scanf(\"%d%d\",&n,&t);int*a=malloc(n*sizeof(int));for(int i=0;i<n;i++)scanf(\"%d\",a+i);int l=0,r=n;while(l<r){int m=l+(r-l)/2;if(a[m]<t)l=m+1;else r=m;}printf(\"%d\",l);free(a);}", cpp:"#include <algorithm>\n#include <iostream>\n#include <vector>\nusing namespace std;\nint main(){int n,t;cin>>n>>t;vector<int>a(n);for(int&x:a)cin>>x;cout<<lower_bound(a.begin(),a.end(),t)-a.begin();}" },
  { title:'二進位 1 數量', topic:'位元運算', difficulty:'簡單', description:'計算無號整數中有多少個 1 bit。', task:'不可轉成字串。', explanation:'n &= n-1 每次清除最低位的 1。', input:'13', output:'3', c:"#include <stdio.h>\nint main(void){unsigned n;int c=0;scanf(\"%u\",&n);while(n){n&=n-1;c++;}printf(\"%d\",c);}", cpp:"#include <iostream>\nusing namespace std;\nint main(){unsigned n;int count=0;cin>>n;while(n){n&=n-1;count++;}cout<<count;}" },
  { title:'各位數總和', topic:'數學', difficulty:'簡單', description:'計算整數絕對值的十進位各位數總和。', task:'負數先去除負號。', explanation:'反覆取餘數 10 並除以 10。', input:'-5072', output:'14', c:"#include <stdio.h>\n#include <stdlib.h>\nint main(void){long long n,s=0;scanf(\"%lld\",&n);n=llabs(n);while(n){s+=n%10;n/=10;}printf(\"%lld\",s);}", cpp:"#include <cstdlib>\n#include <iostream>\nusing namespace std;\nint main(){long long n,s=0;cin>>n;n=llabs(n);for(;n;n/=10)s+=n%10;cout<<s;}" },
  { title:'游程編碼', topic:'字串', difficulty:'中等', description:'把連續相同字元壓縮成字元與次數。', task:'例如 aaabb 轉為 a3b2。', explanation:'每段結束時輸出起始字元與段長。', input:'aaabbcccc', output:'a3b2c4', c:"#include <stdio.h>\nint main(void){char s[100005];scanf(\"%100000s\",s);int c=1;for(int i=1;;i++){if(s[i]==s[i-1])c++;else{printf(\"%c%d\",s[i-1],c);c=1;if(!s[i])break;}}}", cpp:"#include <iostream>\n#include <string>\nusing namespace std;\nint main(){string s;cin>>s;for(int i=0;i<(int)s.size();){int j=i;while(j<(int)s.size()&&s[j]==s[i])j++;cout<<s[i]<<j-i;i=j;}}" },
  { title:'括號是否合法', topic:'stack', difficulty:'中等', description:'檢查三種括號是否正確巢狀配對。', task:'合法輸出 true，否則輸出 false。', explanation:'右括號只能配對最近尚未配對的左括號。', input:'([]){}', output:'true', c:"#include <stdio.h>\nint main(void){char s[100005],st[100005];int top=0,ok=1;scanf(\"%100000s\",s);for(int i=0;s[i]&&ok;i++){char x=s[i];if(x=='('||x=='['||x=='{')st[top++]=x;else{char n=x==')'?'(':x==']'?'[':'{';if(!top||st[--top]!=n)ok=0;}}printf(\"%s\",ok&&!top?\"true\":\"false\");}", cpp:"#include <iostream>\n#include <stack>\n#include <string>\nusing namespace std;\nint main(){string s;stack<char>st;bool ok=true;cin>>s;for(char x:s){if(x=='('||x=='['||x=='{')st.push(x);else{char n=x==')'?'(':x==']'?'[':'{';if(st.empty()||st.top()!=n){ok=false;break;}st.pop();}}cout<<(ok&&st.empty()?\"true\":\"false\");}" },
  { title:'前綴區間和', topic:'前綴和', difficulty:'中等', description:'回答多次閉區間總和查詢。', task:'先讀 n、q、陣列，再讀 q 組 l r，每行輸出答案。', explanation:'prefix[r+1]-prefix[l] 可 O(1) 回答查詢。', input:'5 2\n2 4 1 3 5\n1 3\n0 4', output:'8\n15', c:"#include <stdio.h>\n#include <stdlib.h>\nint main(void){int n,q,l,r;scanf(\"%d%d\",&n,&q);long long*p=calloc(n+1,sizeof(long long));for(int i=0,x;i<n;i++){scanf(\"%d\",&x);p[i+1]=p[i]+x;}while(q--){scanf(\"%d%d\",&l,&r);printf(\"%lld%s\",p[r+1]-p[l],q?\"\\n\":\"\");}free(p);}", cpp:"#include <iostream>\n#include <vector>\nusing namespace std;\nint main(){int n,q;cin>>n>>q;vector<long long>p(n+1);for(int i=0,x;i<n;i++){cin>>x;p[i+1]=p[i]+x;}while(q--){int l,r;cin>>l>>r;cout<<p[r+1]-p[l]<<(q?\"\\n\":\"\");}}" },
];

const pairedProblems = pairSpecs.slice(0, 20).flatMap((spec, index) => {
  const cId = 501 + index;
  const cppId = 521 + index;
  const common = { ...spec, starter: cStarter };
  return [
    makeProblem(cId, 'C', { ...common, description: `${spec.description} 本題要求以 C 的陣列、指標與標準函式庫完成。`, task: `${spec.task} 請提交可直接執行的 C 程式。`, title: spec.title + '（C 實作）', solution: spec.c }, cppId),
    makeProblem(cppId, 'C++', { ...common, starter: cppStarter, description: `${spec.description} 本題要求以 C++ 容器或標準演算法完成。`, task: `${spec.task} 請提交可直接執行的 C++ 程式。`, title: spec.title + '（C++ 實作）', solution: spec.cpp }, cId),
  ];
});

const pythonStarter = "# 讀取輸入並完成程式\n";
const pythonSpecs: Array<Omit<Spec, 'starter'>> = [
  {title:'清理姓名清單',topic:'串列推導',difficulty:'簡單',description:'移除空白、轉小寫並排除空字串。',task:'讀入 JSON 字串陣列並輸出 JSON。',explanation:'串列推導同時表達過濾與轉換。',input:'[" Ada ",""," LINUS"]',output:'["ada","linus"]',solution:"import json\nnames=json.loads(input())\nprint(json.dumps([x.strip().lower() for x in names if x.strip()],separators=(\",\",\":\")))"},
  {title:'保序去重',topic:'dict',difficulty:'簡單',description:'移除重複元素並保留第一次出現順序。',task:'讀入 JSON 陣列並輸出去重結果。',explanation:'dict.fromkeys 會保留插入順序。',input:'[3,1,3,2,1]',output:'[3,1,2]',solution:"import json\nvalues=json.loads(input())\nprint(json.dumps(list(dict.fromkeys(values)),separators=(\",\",\":\")))"},
  {title:'單字長度表',topic:'dict',difficulty:'簡單',description:'建立單字到字元數的對應。',task:'輸出依 key 排序的 JSON 物件。',explanation:'字典推導直接建立 key-value。',input:'["c","python","sql"]',output:'{"c":1,"python":6,"sql":3}',solution:"import json\nwords=json.loads(input())\nprint(json.dumps({w:len(w) for w in words},sort_keys=True,separators=(\",\",\":\")))"},
  {title:'字元頻率',topic:'Counter',difficulty:'簡單',description:'統計非空白字元出現次數。',task:'依字元排序輸出 char:count。',explanation:'Counter 適合統計可雜湊元素。',input:'code code',output:'c:2 d:2 e:2 o:2',solution:"from collections import Counter\nc=Counter(x for x in input() if not x.isspace())\nprint(\" \".join(f\"{x}:{c[x]}\" for x in sorted(c)))"},
  {title:'字母異位詞組數',topic:'雜湊表',difficulty:'中等',description:'計算單字可分成幾組異位詞。',task:'排序字母後作為分組 key。',explanation:'異位詞會得到相同 canonical key。',input:'["eat","tea","tan","ate","nat"]',output:'2',solution:"import json\nwords=json.loads(input())\nprint(len({\"\".join(sorted(w)) for w in words}))"},
  {title:'兩數和索引',topic:'雜湊表',difficulty:'中等',description:'找出兩元素相加為 target 的索引。',task:'讀入 [nums,target] JSON。',explanation:'先查 complement 再寫入，避免重用同一元素。',input:'[[2,7,11,15],9]',output:'[0,1]',solution:"import json\nnums,target=json.loads(input());seen={}\nfor i,x in enumerate(nums):\n if target-x in seen: print(json.dumps([seen[target-x],i],separators=(\",\",\":\")));break\n seen[x]=i"},
  {title:'最長無重複片段',topic:'滑動窗口',difficulty:'中等',description:'找出無重複字元最長子字串長度。',task:'輸出最大長度。',explanation:'last 讓左界直接跳過舊位置。',input:'abcabcbb',output:'3',solution:"s=input();last={};left=best=0\nfor right,ch in enumerate(s):\n if ch in last and last[ch]>=left:left=last[ch]+1\n last[ch]=right;best=max(best,right-left+1)\nprint(best)"},
  {title:'固定窗口平均',topic:'滑動窗口',difficulty:'中等',description:'計算所有長度 k 窗口的平均。',task:'讀入 [nums,k] JSON 並輸出陣列。',explanation:'窗口右移只加入一項並移除一項。',input:'[[1,3,5,7],2]',output:'[2.0,4.0,6.0]',solution:"import json\na,k=json.loads(input());w=sum(a[:k]);out=[w/k]\nfor i in range(k,len(a)):w+=a[i]-a[i-k];out.append(w/k)\nprint(json.dumps(out,separators=(\",\",\":\")))"},
  {title:'島嶼數量',topic:'DFS',difficulty:'中等',description:'計算四向連通的 1 區塊數。',task:'讀入 JSON 0/1 網格。',explanation:'每次從未訪問陸地啟動 DFS 即找到新島。',input:'[[1,1,0],[0,1,0],[1,0,1]]',output:'3',solution:"import json\ng=json.loads(input());R=len(g);C=len(g[0]);seen=set()\ndef dfs(r,c):\n if not(0<=r<R and 0<=c<C) or not g[r][c] or (r,c) in seen:return\n seen.add((r,c))\n for dr,dc in((1,0),(-1,0),(0,1),(0,-1)):dfs(r+dr,c+dc)\nans=0\nfor r in range(R):\n for c in range(C):\n  if g[r][c] and (r,c) not in seen:dfs(r,c);ans+=1\nprint(ans)"},
  {title:'網格最短步數',topic:'BFS',difficulty:'中等',description:'在 0 可走網格找左上到右下最少步數。',task:'無法抵達輸出 -1。',explanation:'BFS 第一次到達終點即為最短路。',input:'[[0,0],[1,0]]',output:'2',solution:"import json\nfrom collections import deque\ng=json.loads(input());R=len(g);C=len(g[0]);q=deque([(0,0,0)]);seen={(0,0)};ans=-1\nwhile q:\n r,c,d=q.popleft()\n if(r,c)==(R-1,C-1):ans=d;break\n for dr,dc in((1,0),(-1,0),(0,1),(0,-1)):\n  nr,nc=r+dr,c+dc\n  if 0<=nr<R and 0<=nc<C and not g[nr][nc] and(nr,nc)not in seen:seen.add((nr,nc));q.append((nr,nc,d+1))\nprint(ans)"},
  {title:'零錢最少枚數',topic:'動態規劃',difficulty:'中等',description:'以指定硬幣湊出 amount 的最少枚數。',task:'無法湊出輸出 -1。',explanation:'dp[value] 從所有可用硬幣轉移。',input:'[[1,2,5],11]',output:'3',solution:"import json\ncoins,amount=json.loads(input());dp=[amount+1]*(amount+1);dp[0]=0\nfor v in range(1,amount+1):\n for c in coins:\n  if c<=v:dp[v]=min(dp[v],dp[v-c]+1)\nprint(-1 if dp[amount]>amount else dp[amount])"},
  {title:'編輯距離',topic:'動態規劃',difficulty:'困難',description:'計算兩字串最少插入、刪除、替換次數。',task:'讀入兩行字串。',explanation:'每格取三種操作來源的最小值。',input:'kitten\nsitting',output:'3',solution:"a=input();b=input();prev=list(range(len(b)+1))\nfor i,x in enumerate(a,1):\n cur=[i]\n for j,y in enumerate(b,1):cur.append(min(cur[-1]+1,prev[j]+1,prev[j-1]+(x!=y)))\n prev=cur\nprint(prev[-1])"},
  {title:'快取費氏數列',topic:'遞迴',difficulty:'中等',description:'用 memoization 計算 F(n)。',task:'輸出第 n 項。',explanation:'快取讓每個子問題只計算一次。',input:'20',output:'6765',solution:"from functools import lru_cache\nn=int(input())\n@lru_cache(None)\ndef f(x):return x if x<2 else f(x-1)+f(x-2)\nprint(f(n))"},
  {title:'合併區間',topic:'排序',difficulty:'中等',description:'合併重疊或相接的閉區間。',task:'讀入 JSON 二維陣列。',explanation:'排序後只需比較最後一段。',input:'[[1,3],[2,6],[8,10]]',output:'[[1,6],[8,10]]',solution:"import json\na=sorted(json.loads(input()));out=[]\nfor s,e in a:\n if not out or s>out[-1][1]:out.append([s,e])\n else:out[-1][1]=max(out[-1][1],e)\nprint(json.dumps(out,separators=(\",\",\":\")))"},
  {title:'清單分塊',topic:'切片',difficulty:'簡單',description:'將清單依 size 切成小清單。',task:'最後一塊可不足 size。',explanation:'range 每次前進 size，再切片一塊。',input:'[[1,2,3,4,5],2]',output:'[[1,2],[3,4],[5]]',solution:"import json\na,k=json.loads(input());print(json.dumps([a[i:i+k] for i in range(0,len(a),k)],separators=(\",\",\":\")))"},
  {title:'矩陣轉置',topic:'zip',difficulty:'簡單',description:'交換矩陣的列與欄。',task:'讀入並輸出 JSON 矩陣。',explanation:'zip(*matrix) 依相同欄位配對。',input:'[[1,2,3],[4,5,6]]',output:'[[1,4],[2,5],[3,6]]',solution:"import json\na=json.loads(input());print(json.dumps([list(x) for x in zip(*a)],separators=(\",\",\":\")))"},
  {title:'括號序列檢查',topic:'stack',difficulty:'中等',description:'檢查三種括號是否完整配對。',task:'輸出 true 或 false。',explanation:'堆疊頂端必須配對目前右括號。',input:'{[()]}',output:'true',solution:"s=input();st=[];pairs={')':'(',']':'[','}':'{'};ok=True\nfor x in s:\n if x in '([{':st.append(x)\n elif not st or st.pop()!=pairs[x]:ok=False;break\nprint(str(ok and not st).lower())"},
  {title:'前 K 大元素',topic:'heapq',difficulty:'中等',description:'輸出最大的 k 個值。',task:'讀入 [nums,k] JSON 並由大到小輸出。',explanation:'nlargest 使用堆積挑出答案。',input:'[[3,1,8,4,9],3]',output:'[9,8,4]',solution:"import heapq,json\na,k=json.loads(input());print(json.dumps(heapq.nlargest(k,a),separators=(\",\",\":\")))"},
  {title:'羅馬數字轉整數',topic:'字串',difficulty:'中等',description:'將合法羅馬數字轉成整數。',task:'支援 I、V、X、L、C、D、M。',explanation:'較小值位於較大值前方時扣除。',input:'MCMXCIV',output:'1994',solution:"s=input();v={'I':1,'V':5,'X':10,'L':50,'C':100,'D':500,'M':1000};total=0\nfor i,x in enumerate(s):total+=-v[x] if i+1<len(s) and v[x]<v[s[i+1]] else v[x]\nprint(total)"},
  {title:'巢狀 JSON 取值',topic:'JSON',difficulty:'中等',description:'依點號路徑安全讀取巢狀物件。',task:'找不到時輸出 null。',explanation:'每層都確認目前值為 dict 且含 key。',input:'{"user":{"name":"Ada"}}\nuser.name',output:'"Ada"',solution:"import json\ncur=json.loads(input())\nfor key in input().split('.'):\n if not isinstance(cur,dict) or key not in cur:cur=None;break\n cur=cur[key]\nprint(json.dumps(cur,separators=(\",\",\":\")))"},
  {title:'日誌等級統計',topic:'Counter',difficulty:'簡單',description:'統計每行第一欄的日誌等級。',task:'第一行為筆數，依等級排序輸出。',explanation:'拆出第一欄後交給 Counter。',input:'4\nINFO start\nERROR bad\nINFO done\nWARN slow',output:'ERROR:1 INFO:2 WARN:1',solution:"from collections import Counter\nn=int(input());c=Counter(input().split(maxsplit=1)[0] for _ in range(n));print(' '.join(f'{x}:{c[x]}' for x in sorted(c)))"},
];

const pythonProblems = pythonSpecs.slice(0, 20).map((spec, index) => makeProblem(541 + index, 'Python', { ...spec, starter: pythonStarter }));

const sqlStarter = "SELECT\n  -- TODO\n;";
const sqlSpecs: Array<Omit<Spec, 'starter'>> = [
  {title:'啟用帳號',topic:'WHERE',difficulty:'簡單',description:'users 表含 id、name、active。',task:'輸出 active=1 的 id、name，依 id 排序。',explanation:'WHERE 篩列，ORDER BY 穩定順序。',input:'users',output:'1|Ada\n3|Linus',solution:"SELECT id, name FROM users WHERE active = 1 ORDER BY id;"},
  {title:'每月營收',topic:'GROUP BY',difficulty:'中等',description:'orders 含 created_at、amount。',task:'依 YYYY-MM 彙總營收。',explanation:'strftime 擷取月份，SUM 彙總。',input:'orders',output:'2026-01|350\n2026-02|80',solution:"SELECT strftime('%Y-%m', created_at) AS month, SUM(amount) AS revenue FROM orders GROUP BY month ORDER BY month;"},
  {title:'客戶終身價值',topic:'JOIN',difficulty:'中等',description:'customers 與 orders 以 customer_id 關聯。',task:'沒有訂單的客戶也輸出 0。',explanation:'LEFT JOIN 保留零訂單客戶。',input:'customers + orders',output:'1|Ada|150\n2|Linus|0',solution:"SELECT c.id, c.name, COALESCE(SUM(o.amount),0) FROM customers c LEFT JOIN orders o ON o.customer_id=c.id GROUP BY c.id,c.name ORDER BY c.id;"},
  {title:'只有未付款訂單的客戶',topic:'條件彙總',difficulty:'中等',description:'找出建立過訂單、但沒有任何 paid 訂單的客戶。',task:'依客戶分組後檢查已付款筆數為零。',explanation:'INNER JOIN 排除零訂單客戶，HAVING 再篩出 paid 計數為零的群組。',input:'customers + orders(status)',output:'2|Linus',solution:"SELECT c.id,c.name FROM customers c JOIN orders o ON o.customer_id=c.id GROUP BY c.id,c.name HAVING SUM(CASE WHEN o.status='paid' THEN 1 ELSE 0 END)=0 ORDER BY c.id;"},
  {title:'第二高不同薪資',topic:'子查詢',difficulty:'中等',description:'找出第二高的不同薪資。',task:'不存在時輸出 NULL。',explanation:'在低於最高薪的集合再取 MAX。',input:'employees',output:'200',solution:"SELECT MAX(salary) AS second_highest FROM employees WHERE salary < (SELECT MAX(salary) FROM employees);"},
  {title:'部門前三薪資',topic:'窗口函式',difficulty:'困難',description:'每個部門取三個最高不同薪資。',task:'同薪同名次且不跳號。',explanation:'DENSE_RANK 適合不同薪資排名。',input:'employees',output:'各部門前三名',solution:"WITH r AS(SELECT employee_id,department_id,salary,DENSE_RANK()OVER(PARTITION BY department_id ORDER BY salary DESC) n FROM employees) SELECT employee_id,department_id,salary FROM r WHERE n<=3 ORDER BY department_id,salary DESC,employee_id;"},
  {title:'累積餘額',topic:'窗口函式',difficulty:'中等',description:'transactions 含 account_id、occurred_at、amount。',task:'計算每帳戶的時間序累積餘額。',explanation:'窗口 SUM 保留每筆明細。',input:'transactions',output:'每筆交易與餘額',solution:"SELECT account_id,occurred_at,amount,SUM(amount)OVER(PARTITION BY account_id ORDER BY occurred_at ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) balance FROM transactions ORDER BY account_id,occurred_at;"},
  {title:'連續登入日',topic:'日期',difficulty:'困難',description:'logins 含 user_id、login_date。',task:'找出至少連續兩天登入者。',explanation:'自連接某日與隔日紀錄。',input:'logins',output:'1\n3',solution:"SELECT DISTINCT a.user_id FROM logins a JOIN logins b ON b.user_id=a.user_id AND b.login_date=date(a.login_date,'+1 day') ORDER BY a.user_id;"},
  {title:'重複 Email',topic:'GROUP BY',difficulty:'簡單',description:'users 的 email 可能重複。',task:'輸出重複的非 NULL email。',explanation:'HAVING 篩選分組後次數。',input:'users',output:'a@example.com',solution:"SELECT email FROM users WHERE email IS NOT NULL GROUP BY email HAVING COUNT(*)>1 ORDER BY email;"},
  {title:'每人最新狀態',topic:'窗口函式',difficulty:'中等',description:'status_history 記錄狀態時間。',task:'每位使用者只保留最新一筆。',explanation:'ROW_NUMBER 精確選每組第一列。',input:'status_history',output:'每人最新狀態',solution:"WITH r AS(SELECT user_id,status,changed_at,ROW_NUMBER()OVER(PARTITION BY user_id ORDER BY changed_at DESC) n FROM status_history) SELECT user_id,status,changed_at FROM r WHERE n=1 ORDER BY user_id;"},
  {title:'購買轉換率',topic:'條件彙總',difficulty:'中等',description:'sessions 含 purchased 0/1。',task:'輸出總工作階段與購買率百分比。',explanation:'CASE 將條件轉成可加總值。',input:'sessions',output:'4|50.0',solution:"SELECT COUNT(*) sessions,ROUND(100.0*SUM(CASE WHEN purchased=1 THEN 1 ELSE 0 END)/COUNT(*),1) conversion_rate FROM sessions;"},
  {title:'次月留存',topic:'CTE',difficulty:'困難',description:'activity 含 user_id、active_month。',task:'計算首月使用者中次月仍活躍人數。',explanation:'先求每人首月，再用 EXISTS 檢查次月。',input:'activity',output:'2',solution:"WITH f AS(SELECT user_id,MIN(active_month) m FROM activity GROUP BY user_id) SELECT COUNT(*) FROM f WHERE EXISTS(SELECT 1 FROM activity a WHERE a.user_id=f.user_id AND a.active_month=date(f.m,'+1 month'));"},
  {title:'組織層級',topic:'遞迴 CTE',difficulty:'困難',description:'employees 含 id、manager_id。',task:'從 id=1 列出所有下屬與深度。',explanation:'錨點建立根，遞迴連接直接下屬。',input:'employees',output:'1|0\n2|1\n3|1',solution:"WITH RECURSIVE org(id,depth)AS(SELECT id,0 FROM employees WHERE id=1 UNION ALL SELECT e.id,org.depth+1 FROM employees e JOIN org ON e.manager_id=org.id) SELECT id,depth FROM org ORDER BY depth,id;"},
  {title:'高於分類平均',topic:'關聯子查詢',difficulty:'中等',description:'products 含 category、name、price。',task:'列出高於自身分類平均的商品。',explanation:'子查詢依外層分類重新計算平均。',input:'products',output:'Pro|30.0',solution:"SELECT p.name,p.price FROM products p WHERE p.price>(SELECT AVG(q.price) FROM products q WHERE q.category=p.category) ORDER BY p.name;"},
  {title:'交易時間間隔',topic:'LAG',difficulty:'中等',description:'events 含 user_id、occurred_at。',task:'顯示每次事件與前次時間。',explanation:'LAG 讀取窗口上一列。',input:'events',output:'事件與前次時間',solution:"SELECT user_id,occurred_at,LAG(occurred_at)OVER(PARTITION BY user_id ORDER BY occurred_at) previous_at FROM events ORDER BY user_id,occurred_at;"},
  {title:'狀態樞紐統計',topic:'CASE',difficulty:'中等',description:'tickets 含 team、status。',task:'每隊輸出 open 與 closed 數量。',explanation:'條件 SUM 把列轉成欄。',input:'tickets',output:'A|2|1\nB|0|2',solution:"SELECT team,SUM(CASE WHEN status='open' THEN 1 ELSE 0 END),SUM(CASE WHEN status='closed' THEN 1 ELSE 0 END) FROM tickets GROUP BY team ORDER BY team;"},
  {title:'庫存結餘',topic:'JOIN',difficulty:'中等',description:'products 與 movements 記錄庫存異動。',task:'輸出所有商品目前庫存。',explanation:'signed quantity 可直接 SUM。',input:'products + movements',output:'1|Keyboard|7\n2|Mouse|0',solution:"SELECT p.id,p.name,COALESCE(SUM(m.quantity),0) stock FROM products p LEFT JOIN movements m ON m.product_id=p.id GROUP BY p.id,p.name ORDER BY p.id;"},
  {title:'第一次訂單',topic:'MIN',difficulty:'簡單',description:'orders 含 customer_id、created_at。',task:'輸出每位客戶第一次下單日期。',explanation:'MIN 取得最早日期。',input:'orders',output:'1|2026-01-02\n2|2026-02-01',solution:"SELECT customer_id,MIN(created_at) first_order_at FROM orders GROUP BY customer_id ORDER BY customer_id;"},
  {title:'註冊月份分群',topic:'日期',difficulty:'中等',description:'users 含 id、created_at。',task:'計算每個註冊月份人數。',explanation:'年月作 cohort key 再計數。',input:'users',output:'2026-01|2\n2026-02|1',solution:"SELECT strftime('%Y-%m',created_at) cohort_month,COUNT(*) users FROM users GROUP BY cohort_month ORDER BY cohort_month;"},
  {title:'缺號偵測',topic:'自連接',difficulty:'困難',description:'sequence_values 含遞增唯一 value。',task:'列出每個缺口的第一個數。',explanation:'不存在 value+1 且尚未到最大值即形成缺口。',input:'sequence_values',output:'3\n7',solution:"SELECT a.value+1 FROM sequence_values a WHERE NOT EXISTS(SELECT 1 FROM sequence_values b WHERE b.value=a.value+1) AND a.value<(SELECT MAX(value) FROM sequence_values) ORDER BY a.value;"},
];

const sqlProblems = sqlSpecs.map((spec, index) => makeProblem(561 + index, 'SQL', { ...spec, starter: sqlStarter }));

const gdbSpecs: Array<Omit<Spec, 'starter'>> = [
  ['啟動並查看參數','中斷點','簡單','在 main 入口暫停並檢查程式參數。','啟動後顯示目前函式參數。','start 會建立暫時中斷點並停在 main。','已載入 ./app','停在 main 並列出參數','start\ninfo args'],
  ['一次性中斷點','中斷點','簡單','只在 init 暫停一次。','使用 temporary breakpoint。','tbreak 命中後自動刪除。','init','暫停一次','tbreak init\nrun'],
  ['條件行中斷點','條件中斷點','中等','只在 worker.c:42 且 id==7 時暫停。','建立條件中斷點。','break 可附加 if 條件。','worker.c:42','id=7 時暫停','break worker.c:42 if id == 7\ncontinue'],
  ['條件監看計數器','watchpoint','中等','count 改變且新值大於 100 時暫停。','建立觀察點後替它加上條件。','可用 $bpnum 指向剛建立的 breakpoint。','count','大於 100 時暫停','watch count\ncondition $bpnum count > 100\ncontinue'],
  ['監看讀取','watchpoint','中等','讀取 *config_ptr 時暫停。','使用 read watchpoint。','rwatch 專門監看讀取。','config_ptr','讀取時暫停','rwatch *config_ptr\ncontinue'],
  ['監看所有存取','watchpoint','中等','buffer[8] 被讀或寫時暫停。','使用 access watchpoint。','awatch 同時監看讀寫。','buffer[8]','存取時暫停','awatch buffer[8]\ncontinue'],
  ['完整呼叫堆疊','呼叫堆疊','簡單','崩潰後顯示完整 backtrace。','包含區域變數。','backtrace full 顯示每層 locals。','SIGSEGV','完整 frames','backtrace full'],
  ['上一層區域變數','呼叫堆疊','中等','移到呼叫者並查看 locals。','依序輸入兩個指令。','up 切換上一層。','frame 0','caller locals','up\ninfo locals'],
  ['檢查函式參數','呼叫堆疊','簡單','顯示目前 frame 的所有參數。','只需一行。','info args 顯示參數。','current frame','arguments','info args'],
  ['十六進位字組','記憶體','中等','從 buffer 顯示 4 個 32-bit word。','使用十六進位 word 格式。','x/NFU 中的 w 表示四位元組 word。','buffer','4 hex words','x/4xw buffer'],
  ['反組譯函式','組合語言','中等','顯示 parse 的機器指令與來源。','使用 mixed source 模式。','/m 混合來源行。','parse','source + assembly','disassemble /m parse'],
  ['查看全部暫存器','暫存器','簡單','列出架構全部暫存器。','使用 info 指令。','all-registers 含額外暫存器。','paused','register values','info all-registers'],
  ['列出執行緒','執行緒','簡單','列出所有執行緒。','標示目前執行緒。','info threads 顯示狀態。','multi-thread','thread list','info threads'],
  ['所有執行緒堆疊','執行緒','困難','一次取得全部 thread 的 backtrace。','對每個 thread 執行 bt。','thread apply all 可套用命令。','deadlock','all backtraces','thread apply all backtrace'],
  ['捕捉 open 系統呼叫','catchpoint','中等','Linux 程式呼叫 open 時暫停。','建立 syscall catchpoint。','catch syscall 可攔截呼叫。','file access','stop at open','catch syscall open\nrun'],
  ['捕捉 C++ 例外','catchpoint','中等','任何 C++ 例外被 throw 時暫停。','建立 throw catchpoint。','catch throw 停在拋出點。','exception','stop at throw','catch throw\nrun'],
  ['載入 core dump','core dump','中等','以 app 與 core.42 重建崩潰現場。','寫出啟動與第一個檢查指令。','需同時指定 executable 與 core。','app + core.42','crash backtrace','gdb ./app core.42\nbacktrace'],
  ['漂亮列印 STL','顯示設定','簡單','啟用結構化列印並查看 values。','設定後 print。','pretty printing 改善巢狀顯示。','values','formatted value','set print pretty on\nprint values'],
  ['持續顯示變數','display','簡單','每次暫停自動顯示 total。','建立 display 後 next。','display 會持續顯示運算式。','total','每步顯示','display total\nnext'],
  ['修改變數後繼續','狀態修改','中等','把 retry 設為 0 後繼續。','使用 set variable。','可用來驗證不同狀態假設。','retry=3','retry=0','set variable retry = 0\ncontinue'],
].map(([title,topic,difficulty,description,task,explanation,input,output,solution]) => ({title,topic,difficulty,description,task,explanation,input,output,solution} as Omit<Spec,'starter'>));

const gdbProblems = gdbSpecs.map((spec, index) => makeProblem(581 + index, 'GDB', { ...spec, starter: '# 輸入 GDB 指令\n' }));

export const uniqueDrillProblems: Problem[] = [...pairedProblems, ...pythonProblems, ...sqlProblems, ...gdbProblems];
