import type { Difficulty, Language, Problem } from './content';

type Spec = {
  title: string;
  topic: string;
  difficulty: Difficulty;
  description: string;
  task: string;
  explanation: string;
  input: string;
  output: string;
  solution: string;
  hidden?: { input: string; output: string };
};

function makeProblem(id: number, language: Language, spec: Spec, pairedProblemId?: number): Problem {
  const starter = language === 'C'
    ? '#include <stdio.h>\n\nint main(void) {\n    // TODO\n    return 0;\n}'
    : language === 'C++'
      ? '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    // TODO\n}'
      : language === 'Python'
        ? '# 讀取輸入並完成程式\n'
        : language === 'SQL'
          ? 'SELECT\n  -- TODO\n;'
          : '# 輸入 GDB 指令\n';
  return {
    id,
    slug: `lab-${id}`,
    title: spec.title,
    language,
    difficulty: spec.difficulty,
    topic: spec.topic,
    track: language === 'SQL' ? '資料庫查詢' : language === 'GDB' ? '除錯實戰' : '核心程式能力',
    acceptance: Math.max(31, 85 - (id % 10) * 4),
    description: spec.description,
    task: spec.task,
    constraints: ['輸出格式必須與題目一致', '必須處理未顯示的邊界資料', '不得寫死範例結果'],
    examples: [{ input: spec.input, output: spec.output }],
    starter,
    solution: spec.solution,
    explanation: spec.explanation,
    hints: ['先把輸入、狀態與輸出拆成小步驟。', spec.explanation],
    checks: [{ label: '公開範例', input: spec.input, output: spec.output, tokens: language === 'GDB' ? spec.solution.split('\n') : ['main'] }],
    pairedProblemId,
  };
}

type PairSpec = Omit<Spec, 'solution'> & { c: string; cpp: string };

const pairs: PairSpec[] = [
  { title: '反轉帶符號整數', topic: '數字', difficulty: '簡單', description: '反轉十進位數字，保留原數正負號。', task: '讀入 long long，輸出反轉後結果；尾零會消失。', explanation: '取絕對值後反覆取個位數，最後還原符號。', input: '-12040', output: '-4021', hidden: { input: '7', output: '7' }, c: '#include <stdio.h>\nint main(void){long long x,r=0,s=1;scanf("%lld",&x);if(x<0){s=-1;x=-x;}do{r=r*10+x%10;x/=10;}while(x);printf("%lld",s*r);}', cpp: '#include <iostream>\nusing namespace std;int main(){long long x,r=0;cin>>x;bool neg=x<0;if(neg)x=-x;do{r=r*10+x%10;x/=10;}while(x);cout<<(neg?-r:r);}' },
  { title: '統計整行元音', topic: '字串', difficulty: '簡單', description: '不分大小寫統計英文元音 aeiou。', task: '讀入一整行文字並輸出元音數。', explanation: '逐字元轉小寫後檢查是否屬於元音集合。', input: 'CodeDive Ocean', output: '7', hidden: { input: 'rhythms', output: '0' }, c: '#include <ctype.h>\n#include <stdio.h>\n#include <string.h>\nint main(void){char s[10005];fgets(s,sizeof s,stdin);int n=0;for(int i=0;s[i];i++)if(strchr("aeiou",tolower((unsigned char)s[i])))n++;printf("%d",n);}', cpp: '#include <algorithm>\n#include <cctype>\n#include <iostream>\n#include <string>\nusing namespace std;int main(){string s;getline(cin,s);cout<<count_if(s.begin(),s.end(),[](unsigned char c){c=tolower(c);return string("aeiou").find(c)!=string::npos;});}' },
  { title: '壓縮連續空白', topic: '字串', difficulty: '中等', description: '把連續空白字元改為一個空格，移除首尾空白。', task: '保留非空白字元順序並輸出正規化文字。', explanation: '用狀態記錄是否正位於空白區段。', input: '  learn   C   now  ', output: 'learn C now', hidden: { input: 'one', output: 'one' }, c: '#include <ctype.h>\n#include <stdio.h>\nint main(void){char s[10005],out[10005];fgets(s,sizeof s,stdin);int k=0,gap=0;for(int i=0;s[i];i++){if(isspace((unsigned char)s[i])){if(k)gap=1;}else{if(gap)out[k++]=\' \';out[k++]=s[i];gap=0;}}out[k]=0;printf("%s",out);}', cpp: '#include <iostream>\n#include <sstream>\n#include <string>\nusing namespace std;int main(){string line,word;getline(cin,line);istringstream in(line);bool first=true;while(in>>word){if(!first)cout<<\' \';cout<<word;first=false;}}' },
  { title: '陣列左輪轉', topic: '陣列', difficulty: '簡單', description: '將陣列循環向左移動 k 格。', task: '第一行 n k，第二行為 n 個整數。', explanation: '先對 k 取 n 餘數，新位置 i 對應舊位置 (i+k)%n。', input: '5 2\n1 2 3 4 5', output: '3 4 5 1 2', hidden: { input: '3 4\n7 8 9', output: '8 9 7' }, c: '#include <stdio.h>\n#include <stdlib.h>\nint main(void){int n,k;scanf("%d%d",&n,&k);int*a=malloc(n*sizeof(int));for(int i=0;i<n;i++)scanf("%d",a+i);k%=n;for(int i=0;i<n;i++)printf("%s%d",i?" ":"",a[(i+k)%n]);free(a);}', cpp: '#include <algorithm>\n#include <iostream>\n#include <vector>\nusing namespace std;int main(){int n,k;cin>>n>>k;vector<int>a(n);for(int&x:a)cin>>x;rotate(a.begin(),a.begin()+k%n,a.end());for(int i=0;i<n;i++)cout<<(i?" ":"")<<a[i];}' },
  { title: '第二大不同值', topic: '陣列', difficulty: '中等', description: '找出陣列中第二大的不同整數。', task: '不足兩個不同值時輸出 NONE。', explanation: '同時維護最大值與第二大值，跳過重複值。', input: '6\n9 2 9 7 5 7', output: '7', hidden: { input: '4\n3 3 3 3', output: 'NONE' }, c: '#include <limits.h>\n#include <stdio.h>\nint main(void){int n,x,a=INT_MIN,b=INT_MIN,ok=0;scanf("%d",&n);while(n--){scanf("%d",&x);if(x>a){if(a!=INT_MIN){b=a;ok=1;}a=x;}else if(x<a&&(x>b||!ok)){b=x;ok=1;}}if(ok)printf("%d",b);else printf("NONE");}', cpp: '#include <iostream>\n#include <set>\nusing namespace std;int main(){int n,x;cin>>n;set<int,greater<int>>s;while(n--){cin>>x;s.insert(x);}if(s.size()<2)cout<<"NONE";else cout<<*next(s.begin());}' },
  { title: '多次區間加總', topic: '前綴和', difficulty: '中等', description: '回答多筆閉區間 [l,r] 的加總。', task: '讀入 n q、陣列與 q 筆查詢，每行輸出一個結果。', explanation: '建立長度 n+1 的前綴和，查詢為 prefix[r+1]-prefix[l]。', input: '5 2\n2 4 6 8 10\n1 3\n0 4', output: '18\n30', hidden: { input: '1 1\n-5\n0 0', output: '-5' }, c: '#include <stdio.h>\n#include <stdlib.h>\nint main(void){int n,q,l,r;scanf("%d%d",&n,&q);long long*p=calloc(n+1,sizeof(long long));for(int i=0,x;i<n;i++){scanf("%d",&x);p[i+1]=p[i]+x;}for(int i=0;i<q;i++){scanf("%d%d",&l,&r);printf("%lld%s",p[r+1]-p[l],i+1<q?"\\n":"");}free(p);}', cpp: '#include <iostream>\n#include <numeric>\n#include <vector>\nusing namespace std;int main(){int n,q;cin>>n>>q;vector<long long>a(n),p(n+1);for(auto&x:a)cin>>x;partial_sum(a.begin(),a.end(),p.begin()+1);while(q--){int l,r;cin>>l>>r;cout<<p[r+1]-p[l]<<(q?"\\n":"");}}' },
  { title: '矩陣轉置', topic: '矩陣', difficulty: '簡單', description: '將 r×c 矩陣的行列交換。', task: '輸出 c×r 轉置矩陣，每列一行。', explanation: '外層走原矩陣的列，內層走原矩陣的行。', input: '2 3\n1 2 3\n4 5 6', output: '1 4\n2 5\n3 6', hidden: { input: '1 3\n7 8 9', output: '7\n8\n9' }, c: '#include <stdio.h>\n#include <stdlib.h>\nint main(void){int r,c;scanf("%d%d",&r,&c);int*a=malloc(r*c*sizeof(int));for(int i=0;i<r*c;i++)scanf("%d",a+i);for(int j=0;j<c;j++)for(int i=0;i<r;i++)printf("%d%s",a[i*c+j],i+1<r?" ":j+1<c?"\\n":"");free(a);}', cpp: '#include <iostream>\n#include <vector>\nusing namespace std;int main(){int r,c;cin>>r>>c;vector a(r,vector<int>(c));for(auto&row:a)for(int&x:row)cin>>x;for(int j=0;j<c;j++){for(int i=0;i<r;i++)cout<<(i?" ":"")<<a[i][j];if(j+1<c)cout<<\'\\n\';}}' },
  { title: '反對角線加總', topic: '矩陣', difficulty: '簡單', description: '計算方陣從右上到左下的反對角線總和。', task: '第一行 n，後續為 n×n 整數。', explanation: '第 i 列所取的列索引是 n-1-i。', input: '3\n1 2 3\n4 5 6\n7 8 9', output: '15', hidden: { input: '1\n-8', output: '-8' }, c: '#include <stdio.h>\nint main(void){int n,x;long long s=0;scanf("%d",&n);for(int i=0;i<n;i++)for(int j=0;j<n;j++){scanf("%d",&x);if(i+j==n-1)s+=x;}printf("%lld",s);}', cpp: '#include <iostream>\n#include <vector>\nusing namespace std;int main(){int n;cin>>n;vector a(n,vector<int>(n));for(auto&row:a)for(int&x:row)cin>>x;long long s=0;for(int i=0;i<n;i++)s+=a[i][n-1-i];cout<<s;}' },
  { title: '科學多項式求值', topic: '數學', difficulty: '中等', description: '以 Horner 法計算多項式在 x 的值。', task: '讀入次數 d、d+1 個由高到低係數與 x。', explanation: '依序更新 result=result*x+coefficient，無需分別求冪。', input: '2\n2 3 4\n5', output: '69', hidden: { input: '0\n-7\n99', output: '-7' }, c: '#include <stdio.h>\nint main(void){int d;long long x,a,r=0;scanf("%d",&d);long long c[1005];for(int i=0;i<=d;i++)scanf("%lld",c+i);scanf("%lld",&x);for(int i=0;i<=d;i++)r=r*x+c[i];printf("%lld",r);}', cpp: '#include <iostream>\n#include <vector>\nusing namespace std;int main(){int d;cin>>d;vector<long long>c(d+1);for(auto&v:c)cin>>v;long long x,r=0;cin>>x;for(long long v:c)r=r*x+v;cout<<r;}' },
  { title: '無符號整數轉二進位', topic: '位元', difficulty: '簡單', description: '將十進位無符號整數轉為不含前導零的二進位。', task: '輸入 0 時必須輸出 0。', explanation: '反覆取除 2 餘數後，將暫存結果反向輸出。', input: '13', output: '1101', hidden: { input: '0', output: '0' }, c: '#include <stdio.h>\nint main(void){unsigned n;char b[33];int k=0;scanf("%u",&n);do{b[k++]=(char)(\'0\'+n%2);n/=2;}while(n);while(k)putchar(b[--k]);}', cpp: '#include <algorithm>\n#include <iostream>\n#include <string>\nusing namespace std;int main(){unsigned n;cin>>n;string b;do{b+=char(\'0\'+n%2);n/=2;}while(n);reverse(b.begin(),b.end());cout<<b;}' },
  { title: '二進位 1 的個數', topic: '位元', difficulty: '中等', description: '計算 32 位無符號整數中有多少個 1。', task: '只輸出計數結果。', explanation: 'C 版本逐位移位檢查，C++ 版本用 bitset 表達固定 32 位。', input: '29', output: '4', hidden: { input: '0', output: '0' }, c: '#include <stdio.h>\nint main(void){unsigned n;int count=0;scanf("%u",&n);for(int bit=0;bit<32;bit++)count+=(n>>bit)&1u;printf("%d",count);}', cpp: '#include <bitset>\n#include <iostream>\nusing namespace std;int main(){unsigned n;cin>>n;cout<<bitset<32>(n).count();}' },
  { title: '驗證 IPv4 位址', topic: '字串解析', difficulty: '中等', description: '判斷文字是否為四個 0 到 255 的十進位段。', task: '合法輸出 valid，否則輸出 invalid。', explanation: '先確認剛好有四段，再檢查每段數值邊界。', input: '192.168.0.1', output: 'valid', hidden: { input: '256.1.2.3', output: 'invalid' }, c: '#include <stdio.h>\nint main(void){char text[64],tail;int a,b,c,d;scanf("%63s",text);int n=sscanf(text,"%d.%d.%d.%d%c",&a,&b,&c,&d,&tail);int ok=n==4&&a>=0&&a<256&&b>=0&&b<256&&c>=0&&c<256&&d>=0&&d<256;printf("%s",ok?"valid":"invalid");}', cpp: '#include <iostream>\n#include <sstream>\n#include <string>\nusing namespace std;int main(){string s,part;cin>>s;stringstream in(s);int count=0;bool ok=true;while(getline(in,part,\'.\')){count++;if(part.empty()||part.size()>3){ok=false;continue;}for(char c:part)if(!isdigit((unsigned char)c))ok=false;if(ok){int v=stoi(part);if(v>255)ok=false;}}cout<<(ok&&count==4?"valid":"invalid");}' },
  { title: '合併兩個已排序陣列', topic: '雙指標', difficulty: '中等', description: '在不重新排序的情況下合併兩個遞增陣列。', task: '讀入 n m 與兩陣列，輸出完整遞增序列。', explanation: '指標比較當前值，每次取較小值並前進。', input: '3 4\n1 4 8\n2 3 9 10', output: '1 2 3 4 8 9 10', hidden: { input: '0 2\n\n5 6', output: '5 6' }, c: '#include <stdio.h>\n#include <stdlib.h>\nint main(void){int n,m;scanf("%d%d",&n,&m);int*a=malloc((n?n:1)*sizeof(int)),*b=malloc((m?m:1)*sizeof(int));for(int i=0;i<n;i++)scanf("%d",a+i);for(int i=0;i<m;i++)scanf("%d",b+i);int i=0,j=0,k=0;while(i<n||j<m){int x=j==m||(i<n&&a[i]<=b[j])?a[i++]:b[j++];printf("%s%d",k++?" ":"",x);}free(a);free(b);}', cpp: '#include <algorithm>\n#include <iostream>\n#include <iterator>\n#include <vector>\nusing namespace std;int main(){int n,m;cin>>n>>m;vector<int>a(n),b(m);for(int&x:a)cin>>x;for(int&x:b)cin>>x;merge(a.begin(),a.end(),b.begin(),b.end(),ostream_iterator<int>(cout," "));}' },
  { title: '唯一交集', topic: '雙指標', difficulty: '中等', description: '找出兩個已排序陣列共有的不同數值。', task: '交集依遞增輸出；沒有交集時輸出空行。', explanation: '相等時輸出並跳過重複，否則前進較小的一側。', input: '5 5\n1 2 2 4 8\n2 2 3 4 9', output: '2 4', hidden: { input: '2 2\n1 2\n3 4', output: '' }, c: '#include <stdio.h>\n#include <stdlib.h>\nint main(void){int n,m;scanf("%d%d",&n,&m);int*a=malloc(n*sizeof(int)),*b=malloc(m*sizeof(int));for(int i=0;i<n;i++)scanf("%d",a+i);for(int j=0;j<m;j++)scanf("%d",b+j);int i=0,j=0,k=0,last=0;while(i<n&&j<m){if(a[i]<b[j])i++;else if(a[i]>b[j])j++;else{if(!k||a[i]!=last){printf("%s%d",k?" ":"",a[i]);last=a[i];k++;}i++;j++;}}free(a);free(b);}', cpp: '#include <algorithm>\n#include <iostream>\n#include <iterator>\n#include <set>\nusing namespace std;int main(){int n,m,x;cin>>n>>m;set<int>a,b;while(n--){cin>>x;a.insert(x);}while(m--){cin>>x;b.insert(x);}set_intersection(a.begin(),a.end(),b.begin(),b.end(),ostream_iterator<int>(cout," "));}' },
  { title: '插入位置 lower bound', topic: '二分搜尋', difficulty: '中等', description: '找出已排序陣列中第一個大於等於 target 的索引。', task: '若所有值都小於 target，輸出 n。', explanation: 'C 版本以遞迴縮小半開區間，C++ 版本以 partition_point 找出條件分界。', input: '6 7\n1 3 7 7 9 12', output: '2', hidden: { input: '3 10\n1 4 8', output: '3' }, c: '#include <stdio.h>\n#include <stdlib.h>\nint lower(const int*a,int left,int right,int target){if(left==right)return left;int middle=left+(right-left)/2;return a[middle]<target?lower(a,middle+1,right,target):lower(a,left,middle,target);}\nint main(void){int n,t;scanf("%d%d",&n,&t);int*a=malloc(n*sizeof(int));for(int i=0;i<n;i++)scanf("%d",a+i);printf("%d",lower(a,0,n,t));free(a);}', cpp: '#include <algorithm>\n#include <iostream>\n#include <vector>\nusing namespace std;int main(){int n,t;cin>>n>>t;vector<int>a(n);for(int&x:a)cin>>x;auto it=partition_point(a.begin(),a.end(),[&](int value){return value<t;});cout<<distance(a.begin(),it);}' },
  { title: '統計局部山峰', topic: '陣列', difficulty: '簡單', description: '統計同時嚴格大於左右相鄰值的內部元素。', task: '第一個與最後一個元素不計算。', explanation: '只需走訪索引 1 到 n-2，同時比較兩側。', input: '7\n1 5 2 4 3 3 0', output: '2', hidden: { input: '4\n1 2 3 4', output: '0' }, c: '#include <stdio.h>\n#include <stdlib.h>\nint main(void){int n,c=0;scanf("%d",&n);int*a=malloc(n*sizeof(int));for(int i=0;i<n;i++)scanf("%d",a+i);for(int i=1;i+1<n;i++)if(a[i]>a[i-1]&&a[i]>a[i+1])c++;printf("%d",c);free(a);}', cpp: '#include <iostream>\n#include <vector>\nusing namespace std;int main(){int n,ans=0;cin>>n;vector<int>a(n);for(int&x:a)cin>>x;for(int i=1;i<n-1;i++)ans+=a[i]>a[i-1]&&a[i]>a[i+1];cout<<ans;}' },
  { title: '最長連續相同段', topic: '陣列', difficulty: '簡單', description: '找出相同值連續出現的最大長度。', task: '陣列至少有一個元素。', explanation: '當前值等於前值就延長，否則從 1 重新計數。', input: '8\n2 2 3 3 3 1 1 4', output: '3', hidden: { input: '5\n9 9 9 9 9', output: '5' }, c: '#include <stdio.h>\nint main(void){int n,p,x,run=1,best=1;scanf("%d%d",&n,&p);for(int i=1;i<n;i++){scanf("%d",&x);run=x==p?run+1:1;if(run>best)best=run;p=x;}printf("%d",best);}', cpp: '#include <algorithm>\n#include <iostream>\nusing namespace std;int main(){int n,p,x,run=1,best=1;cin>>n>>p;while(--n){cin>>x;run=x==p?run+1:1;best=max(best,run);p=x;}cout<<best;}' },
  { title: '眾數且同頻取小', topic: '計數', difficulty: '中等', description: '找出出現次數最多的 0 到 1000 整數。', task: '若多個數值同頻，輸出數值最小者。', explanation: '使用計數陣列，依數值遞增掃描即可自然處理同頻。', input: '7\n4 2 4 3 2 4 2', output: '2', hidden: { input: '3\n8 8 9', output: '8' }, c: '#include <stdio.h>\nint main(void){int n,x,c[1001]={0},best=0;scanf("%d",&n);while(n--){scanf("%d",&x);c[x]++;}for(int i=1;i<=1000;i++)if(c[i]>c[best])best=i;printf("%d",best);}', cpp: '#include <iostream>\n#include <map>\nusing namespace std;int main(){int n,x,b=0,ans=0;map<int,int>c;cin>>n;while(n--){cin>>x;c[x]++;}for(auto [v,f]:c)if(f>b){b=f;ans=v;}cout<<ans;}' },
  { title: '單一類括號平衡', topic: '堆疊', difficulty: '簡單', description: '判斷只包含左右小括號的字串是否平衡。', task: '任一前綴都不可有負平衡值，最後必須回到零。', explanation: '左括號加一、右括號減一，過程為負立即失敗。', input: '(()())', output: 'valid', hidden: { input: '())(', output: 'invalid' }, c: '#include <stdio.h>\nint main(void){char s[100005];int b=0,ok=1;scanf("%100000s",s);for(int i=0;s[i];i++){b+=s[i]==\'(\'?1:-1;if(b<0)ok=0;}printf("%s",ok&&b==0?"valid":"invalid");}', cpp: '#include <iostream>\n#include <string>\nusing namespace std;int main(){string s;cin>>s;int b=0;for(char c:s){b+=c==\'(\'?1:-1;if(b<0)break;}cout<<(b==0?"valid":"invalid");}' },
  { title: '後綴運算式求值', topic: '堆疊', difficulty: '困難', description: '計算空格分隔的整數後綴運算式。', task: '支援 +、-、*、/ 且除法依 C 整數規則。', explanation: '數字入堆疊，運算子取出右、左操作數運算後放回。', input: '5 1 2 + 4 * + 3 -', output: '14', hidden: { input: '2 3 +', output: '5' }, c: '#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\nint main(void){char line[10005],*t;long long s[1000];int top=0;fgets(line,sizeof line,stdin);for(t=strtok(line," \\n");t;t=strtok(NULL," \\n")){if(strlen(t)>1||(t[0]>=\'0\'&&t[0]<=\'9\'))s[top++]=atoll(t);else{long long b=s[--top],a=s[--top];s[top++]=t[0]==\'+\'?a+b:t[0]==\'-\'?a-b:t[0]==\'*\'?a*b:a/b;}}printf("%lld",s[0]);}', cpp: '#include <iostream>\n#include <sstream>\n#include <stack>\n#include <string>\nusing namespace std;int main(){string line,t;getline(cin,line);stringstream in(line);stack<long long>s;while(in>>t){if(t.size()>1||isdigit((unsigned char)t[0]))s.push(stoll(t));else{auto b=s.top();s.pop();auto a=s.top();s.pop();s.push(t=="+"?a+b:t=="-"?a-b:t=="*"?a*b:a/b);}}cout<<s.top();}' },
];

const pairProblems = pairs.flatMap((spec, index) => {
  const cId = 701 + index;
  const cppId = 721 + index;
  return [
    makeProblem(cId, 'C', { ...spec, title: `${spec.title}（C）`, description: `${spec.description} 請以 C 的陣列、指標或標準函式完成。`, task: `${spec.task} 提交可獨立編譯的 C 程式。`, solution: spec.c }, cppId),
    makeProblem(cppId, 'C++', { ...spec, title: `${spec.title}（C++）`, description: `${spec.description} 請以 C++ 容器、迭代器或標準演算法完成。`, task: `${spec.task} 提交可獨立編譯的 C++ 程式。`, solution: spec.cpp }, cId),
  ];
});

const pythonSpecs: Spec[] = [
  { title: '固定大小分塊', topic: '串列切片', difficulty: '簡單', description: '將 JSON 串列每 k 個分成一組。', task: '最後一組可少於 k，輸出緊湊 JSON。', explanation: '以 range(0,len(data),k) 產生每塊起點。', input: '[1,2,3,4,5]\n2', output: '[[1,2],[3,4],[5]]', hidden: { input: '[]\n3', output: '[]' }, solution: "import json\ndata=json.loads(input());k=int(input())\nprint(json.dumps([data[i:i+k] for i in range(0,len(data),k)],separators=(',',':')))" },
  { title: '連續字元分組', topic: 'itertools', difficulty: '中等', description: '把連續相同字元轉為字元與長度。', task: '每組輸出 char:count，以空格分隔。', explanation: 'itertools.groupby 會依連續鍵值分組。', input: 'aaabbcaaaa', output: 'a:3 b:2 c:1 a:4', hidden: { input: 'z', output: 'z:1' }, solution: "from itertools import groupby\ns=input().strip()\nprint(' '.join(f'{ch}:{sum(1 for _ in group)}' for ch,group in groupby(s)))" },
  { title: '展平巢狀字典鍵', topic: '遞迴', difficulty: '中等', description: '將巢狀 JSON 字典轉成點號路徑鍵。', task: '鍵依字母排序後輸出緊湊 JSON。', explanation: '遞迴累積前綴，遇到非字典值才寫入結果。', input: '{"user":{"name":"Ada","score":9}}', output: '{"user.name":"Ada","user.score":9}', hidden: { input: '{"a":1}', output: '{"a":1}' }, solution: "import json\ndata=json.loads(input());out={}\ndef visit(value,path):\n if isinstance(value,dict):\n  for key in sorted(value):visit(value[key],path+[key])\n else:out['.'.join(path)]=value\nvisit(data,[])\nprint(json.dumps(out,separators=(',',':')))" },
  { title: '反轉多對一字典', topic: '集合資料', difficulty: '中等', description: '將 JSON 字典的值改為鍵，原鍵收集成排序串列。', task: '結果鍵與每個串列都要排序。', explanation: '使用 defaultdict(list) 累積後再正規化。', input: '{"a":"x","b":"y","c":"x"}', output: '{"x":["a","c"],"y":["b"]}', hidden: { input: '{"k":"v"}', output: '{"v":["k"]}' }, solution: "import json\nfrom collections import defaultdict\ndata=json.loads(input());out=defaultdict(list)\nfor key,value in data.items():out[str(value)].append(key)\nprint(json.dumps({k:sorted(out[k]) for k in sorted(out)},separators=(',',':')))" },
  { title: 'LRU 快取鍵模擬', topic: 'OrderedDict', difficulty: '困難', description: '模擬容量固定的 LRU 快取，每次存取都把鍵移到最新端。', task: '輸入容量與鍵序列，輸出由舊到新的剩餘鍵。', explanation: 'OrderedDict.move_to_end 和 popitem(last=False) 可直接表達 LRU。', input: '3\na b c a d', output: 'c a d', hidden: { input: '1\nx y', output: 'y' }, solution: "from collections import OrderedDict\ncapacity=int(input());cache=OrderedDict()\nfor key in input().split():\n cache[key]=True;cache.move_to_end(key)\n if len(cache)>capacity:cache.popitem(last=False)\nprint(*cache)" },
  { title: '不等長串列輪流取值', topic: 'itertools', difficulty: '中等', description: '從多個 JSON 串列輪流取一個值，已耗盡串列略過。', task: '保留各串列內部順序並輸出 JSON。', explanation: 'zip_longest 用專用哨兵值補齊，再過濾哨兵。', input: '[[1,2,3],[10],[20,30]]', output: '[1,10,20,2,30,3]', hidden: { input: '[[],[5]]', output: '[5]' }, solution: "import json\nfrom itertools import zip_longest\ndata=json.loads(input());sentinel=object();out=[]\nfor row in zip_longest(*data,fillvalue=sentinel):out.extend(x for x in row if x is not sentinel)\nprint(json.dumps(out,separators=(',',':')))" },
  { title: '遞迴合併設定字典', topic: '遞迴', difficulty: '中等', description: '深層合併兩個 JSON 字典，相同鍵且兩值都是字典時繼續合併。', task: '其他衝突由第二個字典覆蓋。', explanation: '複製左側後逐鍵決定遞迴或覆蓋。', input: '{"db":{"host":"a","port":1},"debug":false}\n{"db":{"port":2},"debug":true}', output: '{"db":{"host":"a","port":2},"debug":true}', hidden: { input: '{"a":1}\n{"b":2}', output: '{"a":1,"b":2}' }, solution: "import json\na=json.loads(input());b=json.loads(input())\ndef merge(left,right):\n out=dict(left)\n for key,value in right.items():out[key]=merge(out[key],value) if key in out and isinstance(out[key],dict) and isinstance(value,dict) else value\n return out\nprint(json.dumps(merge(a,b),sort_keys=True,separators=(',',':')))" },
  { title: '字母序拓撲排序', topic: '圖論', difficulty: '困難', description: '對有向無環圖產生字母序最小的拓撲順序。', task: '節點編號 0..n-1；每次選入度為零的最小編號。', explanation: '使用最小堆維護目前可選節點。', input: '4 3\n0 2\n1 2\n2 3', output: '0 1 2 3', hidden: { input: '3 2\n0 1\n0 2', output: '0 1 2' }, solution: "import heapq\nn,m=map(int,input().split());graph=[[] for _ in range(n)];degree=[0]*n\nfor _ in range(m):\n a,b=map(int,input().split());graph[a].append(b);degree[b]+=1\nheap=[i for i,d in enumerate(degree) if d==0];heapq.heapify(heap);out=[]\nwhile heap:\n node=heapq.heappop(heap);out.append(node)\n for nxt in graph[node]:\n  degree[nxt]-=1\n  if degree[nxt]==0:heapq.heappush(heap,nxt)\nprint(*out)" },
  { title: '單字變換最短步數', topic: 'BFS', difficulty: '困難', description: '每次只改一個字母，在字典中找起點到終點最短距離。', task: '無法到達時輸出 -1。', explanation: '將相差剛好一字元的單字視為相鄰節點做 BFS。', input: 'hit cog\n6\nhot dot dog lot log cog', output: '4', hidden: { input: 'a c\n2\na b', output: '-1' }, solution: "from collections import deque\nstart,end=input().split();n=int(input());words=input().split();queue=deque([(start,0)]);seen={start}\nwhile queue:\n word,distance=queue.popleft()\n if word==end:print(distance);break\n for nxt in words:\n  if nxt not in seen and sum(a!=b for a,b in zip(word,nxt))==1:seen.add(nxt);queue.append((nxt,distance+1))\nelse:print(-1)" },
  { title: '含首尾工作日計數', topic: 'datetime', difficulty: '中等', description: '計算兩個 ISO 日期之間含首尾的週一至週五天數。', task: '不需排除國定假日。', explanation: '由起日逐日向後，weekday()<5 時計數。', input: '2026-09-07 2026-09-13', output: '5', hidden: { input: '2026-09-12 2026-09-13', output: '0' }, solution: "from datetime import date,timedelta\nstart_text,end_text=input().split();day=date.fromisoformat(start_text);end=date.fromisoformat(end_text);count=0\nwhile day<=end:\n count+=day.weekday()<5;day+=timedelta(days=1)\nprint(count)" },
  { title: '解析命名鍵值對', topic: '正規表示式', difficulty: '中等', description: '從 key=value 序列擷取合法鍵與不含空格的值。', task: '鍵只含英文與底線，輸出鍵排序 JSON。', explanation: '用 findall 一次取出命名群組並建立字典。', input: 'name=Ada score=95 lang=C', output: '{"lang":"C","name":"Ada","score":"95"}', hidden: { input: 'x=1', output: '{"x":"1"}' }, solution: "import json,re\npairs=re.findall(r'(?P<key>[A-Za-z_]+)=(?P<value>\\S+)',input())\nprint(json.dumps(dict(sorted(pairs)),separators=(',',':')))" },
  { title: 'Decimal 精確金額加總', topic: 'decimal', difficulty: '簡單', description: '使用 Decimal 累加小數金額，避免二進位浮點誤差。', task: '輸出固定兩位小數。', explanation: '從原文字建立 Decimal，不先轉 float。', input: '0.10 0.20 1.005', output: '1.31', hidden: { input: '2.50 -0.25', output: '2.25' }, solution: "from decimal import Decimal,ROUND_HALF_UP\ntotal=sum(map(Decimal,input().split()),Decimal('0'))\nprint(total.quantize(Decimal('0.01'),rounding=ROUND_HALF_UP))" },
  { title: '多查詢插入索引', topic: 'bisect', difficulty: '簡單', description: '為多個查詢值找在已排序串列的左側插入位置。', task: '第一行串列，第二行查詢；輸出各索引。', explanation: 'bisect_left 回傳第一個大於等於查詢值的位置。', input: '1 3 3 7 9\n0 3 8 10', output: '0 1 4 5', hidden: { input: '5\n5', output: '0' }, solution: "from bisect import bisect_left\nvalues=list(map(int,input().split()));queries=map(int,input().split())\nprint(*(bisect_left(values,q) for q in queries))" },
  { title: '目標和組合', topic: 'itertools', difficulty: '中等', description: '找出串列中所有兩個不同位置的值，使其和等於 target。', task: '每個數對內部排序，去重後輸出 JSON。', explanation: 'combinations(values,2) 枚舉位置組合，再用 set 去重。', input: '[1,2,3,4,5]\n6', output: '[[1,5],[2,4]]', hidden: { input: '[3,3]\n6', output: '[[3,3]]' }, solution: "import json\nfrom itertools import combinations\nvalues=json.loads(input());target=int(input());pairs={tuple(sorted(pair)) for pair in combinations(values,2) if sum(pair)==target}\nprint(json.dumps(sorted(pairs),separators=(',',':')))" },
  { title: '最少零錢枚數', topic: '動態規劃', difficulty: '中等', description: '使用可重複硬幣凑出目標金額，求最少枚數。', task: '無法凑出時輸出 -1。', explanation: 'dp[value] 表示凑出 value 的最少枚數。', input: '3 11\n1 5 7', output: '3', hidden: { input: '1 3\n2', output: '-1' }, solution: "n,target=map(int,input().split());coins=list(map(int,input().split()));dp=[target+1]*(target+1);dp[0]=0\nfor value in range(1,target+1):\n for coin in coins:\n  if coin<=value:dp[value]=min(dp[value],dp[value-coin]+1)\nprint(dp[target] if dp[target]<=target else -1)" },
  { title: '動態中位數', topic: '雙堆積', difficulty: '困難', description: '每讀入一個整數後輸出目前中位數。', task: '偶數個資料時輸出兩中央值的平均，以 .1f 格式。', explanation: '最大堆保留較小半，最小堆保留較大半並維持容量平衡。', input: '5 2 8 1', output: '5.0 3.5 5.0 3.5', hidden: { input: '7', output: '7.0' }, solution: "import heapq\nlow=[];high=[];out=[]\nfor value in map(int,input().split()):\n heapq.heappush(low,-value)\n heapq.heappush(high,-heapq.heappop(low))\n if len(high)>len(low):heapq.heappush(low,-heapq.heappop(high))\n median=float(-low[0]) if len(low)>len(high) else (-low[0]+high[0])/2\n out.append(f'{median:.1f}')\nprint(*out)" },
  { title: '括號最大巢狀深度', topic: '字串', difficulty: '簡單', description: '對已保證平衡的小括號字串計算最大巢狀深度。', task: '左括號進入一層，右括號離開一層。', explanation: '掃描過程維護目前深度與最大值。', input: '(()(()))', output: '3', hidden: { input: '()', output: '1' }, solution: "depth=best=0\nfor char in input().strip():\n if char=='(':depth+=1;best=max(best,depth)\n else:depth-=1\nprint(best)" },
  { title: '查詢字串解碼', topic: 'urllib', difficulty: '中等', description: '將 URL query string 解碼成鍵對多值字典。', task: '保留重複鍵與空值，鍵排序後輸出 JSON。', explanation: 'parse_qs 處理百分比編碼與重複鍵。', input: 'tag=c&tag=cpp&name=Ada%20Lovelace', output: '{"name":["Ada Lovelace"],"tag":["c","cpp"]}', hidden: { input: 'q=', output: '{"q":[""]}' }, solution: "import json\nfrom urllib.parse import parse_qs\ndata=parse_qs(input().strip(),keep_blank_values=True)\nprint(json.dumps(dict(sorted(data.items())),ensure_ascii=False,separators=(',',':')))" },
  { title: '順時針旋轉方陣', topic: '矩陣', difficulty: '中等', description: '將 JSON 方陣順時針旋轉 90 度。', task: '輸出緊湊 JSON 矩陣。', explanation: '對原矩陣倒序列做 zip 即得旋轉結果。', input: '[[1,2],[3,4]]', output: '[[3,1],[4,2]]', hidden: { input: '[[7]]', output: '[[7]]' }, solution: "import json\nmatrix=json.loads(input());rotated=[list(row) for row in zip(*matrix[::-1])]\nprint(json.dumps(rotated,separators=(',',':')))" },
  { title: '座標曼哈頓距離', topic: '資料模型', difficulty: '簡單', description: '使用 namedtuple 表達兩個平面座標，計算曼哈頓距離。', task: '讀入 x1 y1 x2 y2，輸出 |x1-x2|+|y1-y2|。', explanation: '命名欄位讓座標運算更清楚。', input: '1 2 6 -1', output: '8', hidden: { input: '0 0 0 0', output: '0' }, solution: "from collections import namedtuple\nPoint=namedtuple('Point','x y');x1,y1,x2,y2=map(int,input().split());a=Point(x1,y1);b=Point(x2,y2)\nprint(abs(a.x-b.x)+abs(a.y-b.y))" },
];

const sqlSpecs: Spec[] = [
  { title: '員工主管自我連接', topic: 'SELF JOIN', difficulty: '中等', description: '在 employees 同表中對照員工與主管姓名。', task: '保留沒有主管的員工，主管顯示 -。', explanation: '對 employees 設定 employee 與 manager 兩個別名後 LEFT JOIN。', input: 'employees(id,name,manager_id)', output: 'Ada|-\nGrace|Ada\nLinus|-\nKen|Linus', solution: "SELECT e.name, COALESCE(m.name, '-') AS manager\nFROM employees AS e\nLEFT JOIN employees AS m ON m.id = e.manager_id\nORDER BY e.id;" },
  { title: '至少有付款訂單的使用者', topic: 'EXISTS', difficulty: '中等', description: '取得存在 paid 訂單的 users。', task: '輸出 user id 與 name，依 id 排序。', explanation: '關聯 EXISTS 只需確認第一筆匹配，不會複製主表列。', input: 'users 與 orders', output: '1|Ada\n2|Linus\n3|Grace', solution: "SELECT u.id, u.name\nFROM users AS u\nWHERE EXISTS (SELECT 1 FROM orders AS o WHERE o.user_id = u.id AND o.status = 'paid')\nORDER BY u.id;" },
  { title: '完全沒有訂單的使用者', topic: 'NOT EXISTS', difficulty: '中等', description: '找出 orders 中沒有任何關聯列的 users。', task: '不可因 NULL 造成誤判。', explanation: 'NOT EXISTS 直接表達關聯列不存在。', input: 'users 與 orders', output: '4|Ken', solution: 'SELECT u.id, u.name\nFROM users AS u\nWHERE NOT EXISTS (SELECT 1 FROM orders AS o WHERE o.user_id = u.id)\nORDER BY u.id;' },
  { title: '付款與待付金額條件彙總', topic: '條件彙總', difficulty: '中等', description: '每位使用者分別統計 paid 與 pending 金額。', task: '沒有訂單的使用者也要顯示零。', explanation: 'SUM(CASE WHEN...) 可在一次分組中建立多個指標。', input: 'users 與 orders', output: '1|120|80\n2|200|0\n3|50|0\n4|0|0', solution: "SELECT u.id,\n  COALESCE(SUM(CASE WHEN o.status='paid' THEN o.amount ELSE 0 END),0) AS paid_total,\n  COALESCE(SUM(CASE WHEN o.status='pending' THEN o.amount ELSE 0 END),0) AS pending_total\nFROM users AS u LEFT JOIN orders AS o ON o.user_id=u.id\nGROUP BY u.id ORDER BY u.id;" },
  { title: '上一筆訂單金額', topic: 'LAG', difficulty: '中等', description: '在每位使用者的訂單時間線上顯示前一筆金額。', task: '首筆的 previous_amount 為 NULL。', explanation: 'LAG 以 user_id 分區並依 ordered_at 排序。', input: 'orders', output: '101|1|120|\n102|1|80|120\n103|2|200|\n104|3|50|', solution: 'SELECT id,user_id,amount,LAG(amount) OVER(PARTITION BY user_id ORDER BY ordered_at,id) AS previous_amount\nFROM orders ORDER BY user_id,ordered_at,id;' },
  { title: '下一次事件日期', topic: 'LEAD', difficulty: '中等', description: '為同一使用者每筆 event 加上下一筆日期。', task: '最後一筆的 next_day 為 NULL。', explanation: 'LEAD 可不合併列就存取後續列值。', input: 'events', output: '1|2026-01-01|2026-01-03\n1|2026-01-03|\n2|2026-01-02|2026-01-05\n2|2026-01-05|', solution: 'SELECT user_id,day,LEAD(day) OVER(PARTITION BY user_id ORDER BY day) AS next_day\nFROM events ORDER BY user_id,day;' },
  { title: '薪資四分位組', topic: 'NTILE', difficulty: '中等', description: '依薪資由高到低將員工分成四組。', task: '輸出 name、salary 與 bucket。', explanation: 'NTILE(4) 盡量平均分配排序後資料。', input: 'employees', output: 'Linus|130|1\nAda|120|2\nGrace|100|3\nKen|90|4', solution: 'SELECT name,salary,NTILE(4) OVER(ORDER BY salary DESC,id) AS bucket\nFROM employees ORDER BY salary DESC,id;' },
  { title: '部門最高薪姓名', topic: 'FIRST_VALUE', difficulty: '中等', description: '保留每位員工明細，同時顯示所屬部門最高薪者。', task: '同薪資時 id 小者優先。', explanation: 'FIRST_VALUE 在部門分區的降序視窗取第一列。', input: 'employees', output: 'OS|Linus|130|Linus\nOS|Ken|90|Linus\nR&D|Ada|120|Ada\nR&D|Grace|100|Ada', solution: 'SELECT department,name,salary,FIRST_VALUE(name) OVER(PARTITION BY department ORDER BY salary DESC,id) AS top_name\nFROM employees ORDER BY department,salary DESC,id;' },
  { title: '高於部門平均薪資', topic: '關聯子查詢', difficulty: '困難', description: '找出 salary 高於自己 department 平均值的員工。', task: '輸出 id、name、salary，依 id 排序。', explanation: '內層 AVG 透過 department 與外層當前列關聯。', input: 'employees', output: '1|Ada|120\n3|Linus|130', solution: 'SELECT e.id,e.name,e.salary FROM employees AS e\nWHERE e.salary>(SELECT AVG(x.salary) FROM employees AS x WHERE x.department=e.department)\nORDER BY e.id;' },
  { title: '使用者與產品統一搜尋列表', topic: 'UNION ALL', difficulty: '簡單', description: '將 users 與 products 的 id、名稱合併並加上來源標籤。', task: '保留所有列，依 kind、id 排序。', explanation: 'UNION ALL 不做去重，適合明確來源不同的搜尋結果。', input: 'users 與 products', output: 'product|10|IDE\nproduct|11|Book\nproduct|12|Debugger\nproduct|13|Terminal\nuser|1|Ada\nuser|2|Linus\nuser|3|Grace\nuser|4|Ken', solution: "SELECT 'user' AS kind,id,name FROM users\nUNION ALL\nSELECT 'product',id,name FROM products\nORDER BY kind,id;" },
  { title: '每位使用者首筆訂單', topic: 'ROW_NUMBER', difficulty: '中等', description: '依日期取得每位有訂單使用者的第一筆訂單。', task: '同日期時 id 小者優先。', explanation: '在 CTE 內分區編號，外層只保留 row_number=1。', input: 'orders', output: '101|1|120\n103|2|200\n104|3|50', solution: 'WITH ranked AS (SELECT *,ROW_NUMBER() OVER(PARTITION BY user_id ORDER BY ordered_at,id) AS rn FROM orders)\nSELECT id,user_id,amount FROM ranked WHERE rn=1 ORDER BY user_id;' },
  { title: '每月訂單數', topic: '日期彙總', difficulty: '簡單', description: '將 ordered_at 依 YYYY-MM 分組計數。', task: '依月份升序輸出。', explanation: "strftime('%Y-%m',date) 可取得 SQLite 月份鍵。", input: 'orders', output: '2026-01|2\n2026-02|2', solution: "SELECT strftime('%Y-%m',ordered_at) AS month,COUNT(*) AS total\nFROM orders GROUP BY month ORDER BY month;" },
  { title: '姓名長度門檻', topic: '字串函式', difficulty: '簡單', description: '取得姓名長度至少五個字元的 users。', task: '輸出 id 與 name，依 name 排序。', explanation: 'length(name) 回傳 SQLite 文字長度。', input: 'users', output: '3|Grace\n2|Linus', solution: 'SELECT id,name FROM users WHERE length(name)>=5 ORDER BY name;' },
  { title: '包含零的使用者消費總額', topic: 'COALESCE', difficulty: '簡單', description: '統計每位 user 的訂單金額，沒有訂單時顯示零。', task: '保留所有 users，依 id 排序。', explanation: 'LEFT JOIN 保留主表，COALESCE 將 NULL 聚合結果轉零。', input: 'users 與 orders', output: '1|200\n2|200\n3|50\n4|0', solution: 'SELECT u.id,COALESCE(SUM(o.amount),0) AS total\nFROM users AS u LEFT JOIN orders AS o ON o.user_id=u.id\nGROUP BY u.id ORDER BY u.id;' },
  { title: '遞迴產生一到五', topic: '遞迴 CTE', difficulty: '中等', description: '不依賴實體資料表產生 1 到 5 的整數序列。', task: '每個數字輸出一列。', explanation: '錨點查詢產生 1，遞迴部分在值小於 5 時加一。', input: '無', output: '1\n2\n3\n4\n5', solution: 'WITH RECURSIVE numbers(value) AS (SELECT 1 UNION ALL SELECT value+1 FROM numbers WHERE value<5)\nSELECT value FROM numbers;' },
  { title: '使用者訂單累計金額', topic: '窗口加總', difficulty: '中等', description: '依日期顯示每位 user 到目前為止的訂單累計金額。', task: '輸出 order id 與 running_total。', explanation: 'SUM 窗口在 user 分區內依日期展開。', input: 'orders', output: '101|120\n102|200\n103|200\n104|50', solution: 'SELECT id,SUM(amount) OVER(PARTITION BY user_id ORDER BY ordered_at,id ROWS UNBOUNDED PRECEDING) AS running_total\nFROM orders ORDER BY user_id,ordered_at,id;' },
  { title: '產品價格中位數', topic: '窗口位置', difficulty: '困難', description: '計算 products.price 的中位數，偶數筆時取兩中央值平均。', task: '輸出一個 median。', explanation: '先以 ROW_NUMBER 與 COUNT 找中央列，再對中央價格求 AVG。', input: 'products', output: '35.0', solution: 'WITH ranked AS (SELECT price,ROW_NUMBER() OVER(ORDER BY price) AS rn,COUNT(*) OVER() AS n FROM products)\nSELECT AVG(price) FROM ranked WHERE rn IN ((n+1)/2,(n+2)/2);' },
  { title: '事件間隔超過一天', topic: '時間間隔', difficulty: '困難', description: '找出同一 user 連續兩事件間隔大於一天的位置。', task: '輸出 user_id、previous_day、day、gap_days。', explanation: '先以 LAG 取前日，再以 julianday 計算差。', input: 'events', output: '1|2026-01-01|2026-01-03|2\n2|2026-01-02|2026-01-05|3', solution: 'WITH ordered AS (SELECT *,LAG(day) OVER(PARTITION BY user_id ORDER BY day) AS previous_day FROM events)\nSELECT user_id,previous_day,day,CAST(julianday(day)-julianday(previous_day) AS INTEGER) AS gap_days\nFROM ordered WHERE julianday(day)-julianday(previous_day)>1 ORDER BY user_id,day;' },
  { title: '每位使用者購買產品種類數', topic: '多對多關聯', difficulty: '中等', description: '穿過 orders 與 order_items 計算每位 user 購買過的不同 product 數。', task: '沒有購買的 user 也要顯示零。', explanation: '以兩次 LEFT JOIN 保留 users，再 COUNT(DISTINCT product_id)。', input: 'users、orders、order_items', output: '1|2\n2|1\n3|1\n4|0', solution: 'SELECT u.id,COUNT(DISTINCT oi.product_id) AS product_count\nFROM users AS u LEFT JOIN orders AS o ON o.user_id=u.id LEFT JOIN order_items AS oi ON oi.order_id=o.id\nGROUP BY u.id ORDER BY u.id;' },
  { title: '從未被訂購的產品', topic: '反連接', difficulty: '中等', description: '找出 order_items 中不存在關聯列的 products。', task: '輸出 product id 與 name，依 id 排序。', explanation: 'NOT EXISTS 不會受 NULL 影響，可準確表達「沒有任何訂購」。', input: 'products 與 order_items', output: '13|Terminal', solution: 'SELECT p.id,p.name FROM products AS p\nWHERE NOT EXISTS (SELECT 1 FROM order_items AS oi WHERE oi.product_id=p.id)\nORDER BY p.id;' },
];

const gdbRows: Array<[string, string, Difficulty, string, string, string, string, string, string]> = [
  ['臨時中斷點', '中斷點', '中等', '讓 helper 只暫停一次後自動刪除中斷點。', '使用 tbreak 後啟動程式。', 'tbreak 是命中後自動刪除的中斷點。', 'helper 會呼叫兩次', '只在首次 helper 暫停', 'tbreak helper\nrun'],
  ['函式名正規中斷點', '中斷點', '困難', '為所有以 parse_ 開頭的函式設中斷點。', '使用 rbreak 與正規表示式。', 'rbreak 以正規表示式匹配函式名。', 'parse_header parse_body main', '兩個 parse_ 函式有中斷點', 'rbreak ^parse_\nrun'],
  ['條件式中斷點', '中斷點', '中等', '只在迴圈變數 i 等於 50 時暫停。', '先 break 再以 condition 綁定條件。', 'condition 需要中斷點編號與布林運算式。', 'Breakpoint 1', 'i=50 時停下', 'break loop_body\ncondition 1 i == 50\nrun'],
  ['清除特定原始列中斷點', '中斷點管理', '簡單', '移除 main.c 第 20 列的中斷點。', '使用 clear 並指定檔案與列號。', 'clear location 依位置移除中斷點。', 'main.c:20 有 breakpoint', '該位置不再暫停', 'clear main.c:20'],
  ['暫停與恢復中斷點', '中斷點管理', '中等', '暫時停用編號 2，檢查後再恢復。', '依序使用 disable 與 enable。', '停用不會刪除設定，可隨時恢復。', 'Breakpoint 2 enabled', 'off 後回到 on', 'disable 2\ninfo breakpoints\nenable 2'],
  ['跳到指定原始列', '執行控制', '困難', '為驗證修正而直接跳到第 42 列。', '使用 jump 並指定位置。', 'jump 會改變程式計數器，必須留意略過的狀態。', 'paused at line 35', 'next line is 42', 'jump main.c:42'],
  ['強制函式返回', '執行控制', '困難', '讓當前函式立即返回值 -1。', '使用 return -1。', 'return expression 略過剩餘函式內容並設定返回值。', 'inside calculate()', 'caller receives -1', 'return -1'],
  ['在暫停點呼叫函式', '狀態實驗', '中等', '在除錯器中呼叫 strlen(name) 驗證文字長度。', '使用 call 呼叫目標程式函式。', 'call 可產生副作用，只應用於理解的函式。', 'name="Ada"', '$1 = 3', 'call strlen(name)'],
  ['臨時修改變數', '狀態實驗', '中等', '把 count 改為 10 後繼續程式。', '使用 set variable。', 'set variable 修改目標程式記憶體中的值。', 'count=3', 'count=10', 'set variable count = 10\ncontinue'],
  ['取消自動顯示運算式', '觀察狀態', '簡單', '移除編號 1 的 display 運算式。', '使用 undisplay 1。', 'display 項目有自己的編號。', 'display 1: total', 'automatic display removed', 'undisplay 1'],
  ['查詢變數儲存位置', '符號分析', '中等', '查看 global_count 是寄存器、堆疊或固定記憶體位址。', '使用 info address。', 'info address 描述符號目前的儲存類型與位置。', 'global_count symbol loaded', 'static storage address', 'info address global_count'],
  ['向上與向下切換堆疊層', '呼叫堆疊', '中等', '先移到呼叫者，檢查後回當前層。', '使用 up 與 down。', 'up/down 改變當前選擇的 frame，不會改變執行位置。', '#0 worker #1 main', 'select #1 then #0', 'up\ninfo locals\ndown'],
  ['所有執行緒呼叫堆疊', '多執行緒', '困難', '一次列出每個執行緒的 backtrace。', '使用 thread apply all bt。', '比單純 info threads 更能比較所有執行緒的卡住位置。', 'four threads paused', 'four backtraces', 'thread apply all bt'],
  ['只在特定執行緒中停下', '多執行緒', '困難', '把 worker 中斷點限制在執行緒 3。', '在 break 位置後加上 thread 3 限定。', '執行緒限定可避免其他執行緒命中同一份函式程式碼。', 'multiple workers', 'only thread 3 stops', 'break worker thread 3\ncontinue'],
  ['捕捉檔案開啟系統呼叫', '系統呼叫', '困難', '在程式進入 openat 系統呼叫時暫停。', '使用 catch syscall openat。', '系統呼叫 catchpoint 適合找出檔案或網路操作來源。', 'program opens config file', 'stop at openat', 'catch syscall openat\nrun'],
  ['設定 SIGPIPE 處理', '信號', '中等', '讓 SIGPIPE 發生時不暫停但仍通知程式。', '使用 handle SIGPIPE nostop pass。', 'handle 同時決定 GDB 是否暫停、列印與傳給程式。', 'SIGPIPE received', 'program handles signal', 'handle SIGPIPE nostop pass'],
  ['混合原始碼反組譯', '組合語言', '困難', '對 calculate 顯示原始碼與組合語言對照。', '使用 disassemble /m calculate。', '/m 模式將指令排在對應原始列旁。', 'debug symbols loaded', 'mixed source and assembly', 'disassemble /m calculate'],
  ['限制容器列印長度', '輸出格式', '中等', '查看大型陣列時只顯示前 20 個元素。', '使用 set print elements 20。', '限制元素數可避免大型容器輸出淹沒關鍵狀態。', 'array has 10000 values', 'first 20 values shown', 'set print elements 20\nprint values'],
  ['產生 core dump 檔', '事後分析', '困難', '將當前暫停狀態儲存為 core 檔。', '使用 generate-core-file。', 'core 檔保留記憶體與寄存器狀態供離線分析。', 'paused process', 'core file saved', 'generate-core-file core.debug'],
  ['查看可執行檔區段佈局', '二進位分析', '困難', '列出 .text、.data 與 .bss 等載入區段範圍。', '使用 maintenance info sections。', '區段佈局可幫助判斷位址屬於程式碼、已初始化或未初始化資料。', 'executable loaded', 'section address ranges', 'maintenance info sections'],
];

export const uniqueProgramHiddenCasesV3: Record<number, { input: string; output: string }> = {};
for (const [index, spec] of pairs.entries()) {
  if (spec.hidden) {
    uniqueProgramHiddenCasesV3[701 + index] = spec.hidden;
    uniqueProgramHiddenCasesV3[721 + index] = spec.hidden;
  }
}
for (const [index, spec] of pythonSpecs.entries()) if (spec.hidden) uniqueProgramHiddenCasesV3[741 + index] = spec.hidden;

const pythonProblems = pythonSpecs.map((spec, index) => makeProblem(741 + index, 'Python', spec));
const sqlProblems = sqlSpecs.map((spec, index) => makeProblem(761 + index, 'SQL', spec));
const gdbProblems = gdbRows.map(([title, topic, difficulty, description, task, explanation, input, output, solution], index) =>
  makeProblem(781 + index, 'GDB', { title, topic, difficulty, description, task, explanation, input, output, solution }),
);

export const uniqueDrillProblemsV3: Problem[] = [...pairProblems, ...pythonProblems, ...sqlProblems, ...gdbProblems];
