import type { PlaygroundExample, PlaygroundLanguage } from './playground-library';

export const extraPlaygroundExamples: Record<PlaygroundLanguage, PlaygroundExample[]> = {
  C: [
    { id: 'c-list', title: '單向鏈結串列', category: '資料結構', summary: '動態建立節點、走訪並完整釋放。', stdin: '4\n8 3 5 2', concepts: ['struct', 'linked list', 'free'], source: '#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct Node { int value; struct Node *next; } Node;\n\nint main(void) {\n    int n, value; scanf("%d", &n);\n    Node *head = NULL, **tail = &head;\n    while (n-- && scanf("%d", &value) == 1) {\n        *tail = malloc(sizeof(Node));\n        if (*tail == NULL) return 1;\n        (*tail)->value = value; (*tail)->next = NULL; tail = &(*tail)->next;\n    }\n    for (Node *node = head; node; node = node->next) printf("%d ", node->value);\n    while (head) { Node *next = head->next; free(head); head = next; }\n    return 0;\n}' },
    { id: 'c-bits', title: '位元旗標', category: '位元運算', summary: '用遮罩開啟、關閉與測試選項。', stdin: '2', concepts: ['bit mask', '|', '&'], source: '#include <stdio.h>\n\nint main(void) {\n    unsigned option; scanf("%u", &option);\n    unsigned flags = 0;\n    flags |= 1u << option;\n    printf("enabled=%u flags=%u\\n", (flags & (1u << option)) != 0, flags);\n    flags &= ~(1u << option);\n    printf("flags=%u\\n", flags);\n    return 0;\n}' },
    { id: 'c-binary-search', title: '二分搜尋', category: '演算法', summary: '在已排序陣列中縮小搜尋區間。', stdin: '6 11\n2 4 7 11 15 20', concepts: ['binary search', 'left', 'right'], source: '#include <stdio.h>\n\nint main(void) {\n    int n, target, values[1000]; scanf("%d%d", &n, &target);\n    for (int i = 0; i < n; i++) scanf("%d", &values[i]);\n    int left = 0, right = n - 1, answer = -1;\n    while (left <= right) {\n        int middle = left + (right - left) / 2;\n        if (values[middle] == target) { answer = middle; break; }\n        if (values[middle] < target) left = middle + 1; else right = middle - 1;\n    }\n    printf("%d\\n", answer);\n    return 0;\n}' },
    { id: 'c-recursion', title: '遞迴計算最大公因數', category: '函式', summary: '用歐幾里得遞迴展示基底條件。', stdin: '84 30', concepts: ['recursion', 'base case', 'modulo'], source: '#include <stdio.h>\n\nint gcd(int a, int b) { return b == 0 ? a : gcd(b, a % b); }\n\nint main(void) {\n    int a, b; scanf("%d%d", &a, &b);\n    printf("%d\\n", gcd(a, b));\n    return 0;\n}' },
    { id: 'c-function-pointer', title: '函式指標切換運算', category: '進階語法', summary: '將函式當作參數，在執行期選擇行為。', stdin: '* 6 7', concepts: ['function pointer', 'callback', 'switch'], source: '#include <stdio.h>\n\nint add(int a, int b) { return a + b; }\nint multiply(int a, int b) { return a * b; }\n\nint main(void) {\n    char op; int a, b; scanf(" %c%d%d", &op, &a, &b);\n    int (*operation)(int, int) = op == \'*\' ? multiply : add;\n    printf("%d\\n", operation(a, b));\n    return 0;\n}' },
  ],
  'C++': [
    { id: 'cpp-stack', title: '括號配對堆疊', category: '資料結構', summary: '堆疊保留尚未配對的左括號。', stdin: '{[()]}', concepts: ['stack', 'matching', 'string'], source: '#include <iostream>\n#include <stack>\n#include <string>\nusing namespace std;\n\nint main() {\n    string text; cin >> text; stack<char> opened; bool valid = true;\n    for (char ch : text) {\n        if (ch == \'(\' || ch == \'[\' || ch == \'{\') opened.push(ch);\n        else {\n            if (opened.empty()) { valid = false; break; }\n            char left = opened.top(); opened.pop();\n            if ((ch == \')\' && left != \'(\') || (ch == \']\' && left != \'[\') || (ch == \'}\' && left != \'{\')) valid = false;\n        }\n    }\n    cout << (valid && opened.empty() ? "valid" : "invalid") << \'\\n\';\n}' },
    { id: 'cpp-set', title: 'set 集合交集', category: '資料結構', summary: '結合 set_intersection 取得已排序交集。', stdin: '4 5\n1 3 5 7\n2 3 5 7 9', concepts: ['set', 'set_intersection', 'iterator'], source: '#include <algorithm>\n#include <iostream>\n#include <iterator>\n#include <set>\nusing namespace std;\n\nint main() {\n    int n, m, value; cin >> n >> m; set<int> a, b;\n    while (n--) { cin >> value; a.insert(value); }\n    while (m--) { cin >> value; b.insert(value); }\n    set_intersection(a.begin(), a.end(), b.begin(), b.end(), ostream_iterator<int>(cout, " "));\n}' },
    { id: 'cpp-multimap', title: 'map 分組排序', category: '關聯容器', summary: '以 map 依鍵排序，每組保留多個值。', stdin: '4\nB Linus\nA Ada\nA Grace\nB Dennis', concepts: ['map', 'vector', 'structured binding'], source: '#include <iostream>\n#include <map>\n#include <string>\n#include <vector>\nusing namespace std;\n\nint main() {\n    int n; cin >> n; map<string, vector<string>> groups;\n    while (n--) { string key, value; cin >> key >> value; groups[key].push_back(value); }\n    for (const auto &[key, values] : groups) { cout << key << \':\'; for (const string &value : values) cout << \' \' << value; cout << \'\\n\'; }\n}' },
    { id: 'cpp-dfs', title: '遞迴深度優先搜尋', category: '圖論', summary: '逐枝探索圖，用 visited 防止重複。', stdin: '', concepts: ['DFS', 'recursion', 'visited'], source: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nvoid dfs(int node, const vector<vector<int>> &graph, vector<bool> &seen) {\n    seen[node] = true; cout << node << \' \';\n    for (int next : graph[node]) if (!seen[next]) dfs(next, graph, seen);\n}\n\nint main() {\n    vector<vector<int>> graph{{1, 2}, {3}, {3}, {}}; vector<bool> seen(graph.size());\n    dfs(0, graph, seen);\n}' },
    { id: 'cpp-lambda', title: 'lambda 自訂累加', category: '現代 C++', summary: '以 lambda 封裝條件，只累加偶數。', stdin: '6\n1 2 3 4 5 6', concepts: ['lambda', 'accumulate', 'capture'], source: '#include <iostream>\n#include <numeric>\n#include <vector>\nusing namespace std;\n\nint main() {\n    int n; cin >> n; vector<int> values(n); for (int &value : values) cin >> value;\n    int total = accumulate(values.begin(), values.end(), 0, [](int sum, int value) { return value % 2 == 0 ? sum + value : sum; });\n    cout << total << \'\\n\';\n}' },
  ],
  Python: [
    { id: 'py-set', title: '集合去重與差集', category: '資料結構', summary: '用 set 線性去重，再比較兩集合。', stdin: '1 2 2 3 5\n2 4 5', concepts: ['set', 'difference', 'sorted'], source: 'left = set(map(int, input().split()))\nright = set(map(int, input().split()))\nprint(*sorted(left - right))' },
    { id: 'py-dataclass', title: 'dataclass 排序記錄', category: '物件資料', summary: '以資料類別表達紀錄，再依成績排序。', stdin: '', concepts: ['dataclass', 'sorted', 'key'], source: 'from dataclasses import dataclass\n\n@dataclass\nclass Student:\n    name: str\n    score: int\n\nstudents = [Student("Ada", 91), Student("Grace", 95), Student("Linus", 87)]\nfor student in sorted(students, key=lambda item: (-item.score, item.name)):\n    print(student.name, student.score)' },
    { id: 'py-regex', title: '正規表示式命名群組', category: '文字處理', summary: '從日期文字擷取年、月、日。', stdin: '2026-09-10', concepts: ['re.fullmatch', 'named group', 'groupdict'], source: 'import re\n\nmatch = re.fullmatch(r"(?P<year>\\d{4})-(?P<month>\\d{2})-(?P<day>\\d{2})", input().strip())\nif match:\n    print(match.group("day"), match.group("month"), match.group("year"))\nelse:\n    print("invalid")' },
    { id: 'py-itertools', title: 'itertools 直積組合', category: '標準工具', summary: '使用 product 產生所有座標組合。', stdin: '', concepts: ['itertools', 'product', 'tuple'], source: 'from itertools import product\n\nrows = range(2)\ncolumns = range(3)\nprint(*product(rows, columns))' },
    { id: 'py-cache', title: '記憶化遞迴', category: '動態規劃', summary: '以 cache 避免費氏數列重複計算。', stdin: '12', concepts: ['functools.cache', 'recursion', 'memoization'], source: 'from functools import cache\n\n@cache\ndef fibonacci(n):\n    if n < 2:\n        return n\n    return fibonacci(n - 1) + fibonacci(n - 2)\n\nprint(fibonacci(int(input())))' },
  ],
  SQL: [
    { id: 'sql-subquery', title: '高於平均值的資料', category: '子查詢', summary: '在 WHERE 中使用標量子查詢。', stdin: '', concepts: ['subquery', 'AVG', 'WHERE'], source: "CREATE TABLE scores(name TEXT, score INTEGER);\nINSERT INTO scores VALUES ('Ada', 95), ('Grace', 88), ('Linus', 70);\n\nSELECT name, score\nFROM scores\nWHERE score > (SELECT AVG(score) FROM scores)\nORDER BY score DESC;" },
    { id: 'sql-case', title: 'CASE 條件分類', category: '資料轉換', summary: '把連續分數轉成可讀的等級。', stdin: '', concepts: ['CASE', 'WHEN', 'alias'], source: "CREATE TABLE scores(name TEXT, score INTEGER);\nINSERT INTO scores VALUES ('Ada', 95), ('Grace', 82), ('Linus', 60);\n\nSELECT name, CASE\n  WHEN score >= 90 THEN 'A'\n  WHEN score >= 80 THEN 'B'\n  ELSE 'C'\nEND AS grade\nFROM scores\nORDER BY name;" },
    { id: 'sql-self-join', title: '員工與主管對照', category: '資料表關聯', summary: '同一張表使用兩個別名做自我連接。', stdin: '', concepts: ['SELF JOIN', 'alias', 'LEFT JOIN'], source: "CREATE TABLE employees(id INTEGER, name TEXT, manager_id INTEGER);\nINSERT INTO employees VALUES (1, 'Ada', NULL), (2, 'Grace', 1), (3, 'Linus', 1);\n\nSELECT employee.name, COALESCE(manager.name, '-') AS manager\nFROM employees AS employee\nLEFT JOIN employees AS manager ON manager.id = employee.manager_id\nORDER BY employee.id;" },
    { id: 'sql-exists', title: 'EXISTS 存在性查詢', category: '子查詢', summary: '只取得至少有一筆匹配資料的主記錄。', stdin: '', concepts: ['EXISTS', 'correlated subquery', 'SELECT 1'], source: "CREATE TABLE users(id INTEGER, name TEXT);\nCREATE TABLE orders(id INTEGER, user_id INTEGER);\nINSERT INTO users VALUES (1, 'Ada'), (2, 'Linus');\nINSERT INTO orders VALUES (10, 1);\n\nSELECT id, name\nFROM users AS user\nWHERE EXISTS (SELECT 1 FROM orders WHERE orders.user_id = user.id);" },
    { id: 'sql-date', title: '按月彙總日期', category: '時間分析', summary: '使用 SQLite strftime 把日期分組到月份。', stdin: '', concepts: ['strftime', 'GROUP BY', 'COUNT'], source: "CREATE TABLE events(occurred_at TEXT);\nINSERT INTO events VALUES ('2026-01-02'), ('2026-01-20'), ('2026-02-03');\n\nSELECT strftime('%Y-%m', occurred_at) AS month, COUNT(*) AS total\nFROM events\nGROUP BY month\nORDER BY month;" },
  ],
  GDB: [
    { id: 'gdb-break', title: '從 main 中斷點開始', category: '入門', summary: '設定中斷點、啟動程式並查看區域變數。', stdin: '5', concepts: ['break', 'run', 'info locals'], source: 'break main\nrun\nnext\ninfo locals\ncontinue', targetSource: '#include <stdio.h>\nint main(void) { int value; scanf("%d", &value); int square = value * value; printf("%d\\n", square); return 0; }' },
    { id: 'gdb-step', title: '進入函式追蹤參數', category: '單步執行', summary: '比較 next 與 step，進入函式後查看參數。', stdin: '7 4', concepts: ['step', 'info args', 'finish'], source: 'break main\nrun\nnext\nstep\ninfo args\nfinish\ncontinue', targetSource: '#include <stdio.h>\nint difference(int a, int b) { return a - b; }\nint main(void) { int a, b; scanf("%d%d", &a, &b); printf("%d\\n", difference(a, b)); }' },
    { id: 'gdb-watch', title: '監看變數何時改變', category: '資料中斷點', summary: '以 watch 在 total 被寫入時暫停。', stdin: '', concepts: ['watch', 'continue', 'display'], source: 'break main\nrun\nnext\nwatch total\ndisplay total\ncontinue\ncontinue', targetSource: '#include <stdio.h>\nint main(void) { int total = 0; for (int i = 1; i <= 3; i++) total += i; printf("%d\\n", total); }' },
    { id: 'gdb-backtrace', title: '用呼叫堆疊找錯', category: '呼叫堆疊', summary: '在深層函式暫停，使用 backtrace 查看來源。', stdin: '', concepts: ['backtrace', 'frame', 'up'], source: 'break level_three\nrun\nbacktrace\nframe 1\ninfo locals\nup\ncontinue', targetSource: '#include <stdio.h>\nvoid level_three(void) { puts("deep"); }\nvoid level_two(void) { level_three(); }\nvoid level_one(void) { level_two(); }\nint main(void) { level_one(); }' },
    { id: 'gdb-condition', title: '條件式中斷點', category: '中斷點', summary: '只在迴圈變數符合條件時停下。', stdin: '', concepts: ['condition', 'breakpoint', 'print'], source: 'break main\nrun\nbreak 2\ncondition 2 i == 3\ncontinue\nprint i\ncontinue', targetSource: '#include <stdio.h>\nint main(void) { for (int i = 0; i < 5; i++) printf("%d ", i); }' },
    { id: 'gdb-array', title: '檢視陣列記憶體', category: '記憶體', summary: '以 x 指令從陣列位址顯示多個整數。', stdin: '', concepts: ['x/5dw', 'address', 'array'], source: 'break main\nrun\nnext\nx/5dw &values\nprint values[2]\ncontinue', targetSource: '#include <stdio.h>\nint main(void) { int values[] = {10, 20, 30, 40, 50}; printf("%d\\n", values[2]); }' },
    { id: 'gdb-segfault', title: '追蹤空指標崩潰', category: '錯誤定位', summary: '捕捉 SIGSEGV 後查看堆疊與指標。', stdin: '', concepts: ['signal', 'backtrace', 'print pointer'], source: 'handle SIGSEGV stop print\nrun\nbacktrace\nprint pointer\ninfo locals', targetSource: '#include <stdio.h>\nint main(void) { int *pointer = NULL; printf("%d\\n", *pointer); }' },
    { id: 'gdb-tbreak', title: '只停一次的中斷點', category: '中斷點', summary: '用 tbreak 設置命中後自動刪除的中斷點。', stdin: '', concepts: ['tbreak', 'continue', 'info breakpoints'], source: 'tbreak helper\nrun\ninfo breakpoints\ncontinue', targetSource: '#include <stdio.h>\nvoid helper(void) { puts("once"); }\nint main(void) { helper(); helper(); }' },
    { id: 'gdb-set', title: '臨時修改變數驗證假設', category: '狀態實驗', summary: '暫停後用 set variable 改值，再繼續執行。', stdin: '3', concepts: ['set variable', 'print', 'continue'], source: 'break main\nrun\nnext\nset variable count = 10\nprint count\ncontinue', targetSource: '#include <stdio.h>\nint main(void) { int count; scanf("%d", &count); printf("%d\\n", count * 2); }' },
    { id: 'gdb-disassemble', title: '對照原始碼與組合語言', category: '底層觀察', summary: '在函式入口查看混合反組譯。', stdin: '6', concepts: ['disassemble /m', 'registers', 'assembly'], source: 'break cube\nrun\ndisassemble /m cube\ninfo registers\ncontinue', targetSource: '#include <stdio.h>\nint cube(int value) { return value * value * value; }\nint main(void) { int value; scanf("%d", &value); printf("%d\\n", cube(value)); }' },
  ],
};
